(function(){var a=document.uniqueID&&document.compatMode&&!window.XMLHttpRequest&&document.execCommand;try{a&&a("BackgroundImageCache",!1,!0)}catch(b){}var c=navigator.userAgent.toLowerCase(),a=function(a){return-1!=c.indexOf(a)};jQuery("html").addClass([!/opera|webtv/i.test(c)&&/msie (\d)/.test(c)?"ie ie"+RegExp.$1:a("firefox/2")?"gecko firefox2":a("firefox/3")?"gecko firefox3":a("gecko/")?"gecko":a("chrome/")?"chrome":a("opera/9")?"opera opera9":/opera (\d)/.test(c)?"opera opera"+RegExp.$1:a("konqueror")?
"konqueror":a("applewebkit/")?"webkit safari":a("mozilla/")?"gecko":"",a("x11")||a("linux")?" linux":a("mac")?" mac":a("win")?" win":""].join(" "))})();var _artStyleUrlCached=null;
function artGetStyleUrl(){if(null==_artStyleUrlCached){var a;_artStyleUrlCached="";a=jQuery("link");for(var b=0;b<a.length;b++){var c=a[b].href;if(c&&/style\.ie6\.css(\?.*)?$/.test(c))return _artStyleUrlCached=c.replace(/style\.ie6\.css(\?.*)?$/,"")}a=jQuery("style");for(b=0;b<a.length;b++)if(c=/import\s+"([^"]+\/)style\.ie6\.css"/.exec(a[b].html()),null!=c&&0<c.length)return _artStyleUrlCached=c[1]}return _artStyleUrlCached}
function artFixPNG(a){if(jQuery.browser.msie&&7>parseInt(jQuery.browser.version)){var b;if("IMG"==a.tagName)/\.png$/.test(a.src)&&(b=a.src,a.src=artGetStyleUrl()+"images/spacer.gif");else if(b=a.currentStyle.backgroundImage.match(/url\("(.+\.png)"\)/i))b=b[1],a.runtimeStyle.backgroundImage="none";b&&(a.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src\x3d'"+b+"')")}}
jQuery(function(){jQuery.each(jQuery("ul.art-menu\x3eli,ul.art-vmenu\x3eli"),function(a,b){var c=jQuery(b),d=c.children("span");if(0!=d.length){var e=c.find("span.t").last();c.children("a").append(e.html(e.text()));d.remove()}})});
jQuery(function(){jQuery.each(jQuery("ul.art-menu\x3eli:not(:last-child)"),function(a,b){jQuery('\x3cli class\x3d"art-menu-li-separator"\x3e\x3cspan class\x3d"art-menu-separator"\x3e \x3c/span\x3e\x3c/li\x3e').insertAfter(b)});!jQuery.browser.msie||6<parseInt(jQuery.browser.version)||jQuery.each(jQuery("ul.art-menu li"),function(a,b){b.j=jQuery(b);b.UL=b.j.children("ul:first");0!=b.UL.length&&(b.A=b.j.children("a:first"),this.onmouseenter=function(){this.j.addClass("art-menuhover");this.UL.addClass("art-menuhoverUL");
this.A.addClass("art-menuhoverA")},this.onmouseleave=function(){this.j.removeClass("art-menuhover");this.UL.removeClass("art-menuhoverUL");this.A.removeClass("art-menuhoverA")})})});
jQuery(function(){if(jQuery.browser.msie&&!(7<parseInt(jQuery.browser.version))){var a=jQuery("div.art-content");if(1===a.length){var b=a.parent().children(".art-layout-cell:not(.art-content)");jQuery(window).bind("resize",function(){if(a.w!=a.parent().width()){var c=0;a.css("width","0");b.each(function(){c+=this.clientWidth});a.w=a.parent().width();a.css("width",a.w-c)}}).trigger("resize");jQuery("div.art-content-layout-row").each(function(){this.c=jQuery(this).children(".art-layout-cell")}).bind("resize",
function(){this.h!=this.clientHeight&&(this.c.css("height","auto"),this.h=this.clientHeight,this.c.css("height",this.h+"px"))}).trigger("resize")}}});
function artButtonSetup(a){jQuery.each(jQuery("a."+a+", button."+a+", input."+a),function(a,c){var d=jQuery(c);d.parent().hasClass("art-button-wrapper")||(d.hasClass("art-button")||d.addClass("art-button"),jQuery("\x3cspan class\x3d'art-button-wrapper'\x3e\x3cspan class\x3d'art-button-l'\x3e \x3c/span\x3e\x3cspan class\x3d'art-button-r'\x3e \x3c/span\x3e\x3c/span\x3e").insertBefore(d).append(d),d.hasClass("active")&&d.parent().addClass("active"));d.mouseover(function(){jQuery(this).parent().addClass("hover")});
d.mouseout(function(){var a=jQuery(this);a.parent().removeClass("hover");a.hasClass("active")||a.parent().removeClass("active")});d.mousedown(function(){var a=jQuery(this);a.parent().removeClass("hover");a.hasClass("active")||a.parent().addClass("active")});d.mouseup(function(){var a=jQuery(this);a.hasClass("active")||a.parent().removeClass("active")})})}jQuery(function(){artButtonSetup("art-button")});jQuery(function(){artButtonSetup("button");artButtonSetup("readon");artButtonSetup("readmore")});