var tabMenuOptions={menuId:"tabmenu",linkIdToMenuHtml:null,preview:!0,delay:200,speed:0.04,license:"2c8m1"},tabmenu=new McTabMenu(tabMenuOptions);
function McTabMenu(m){var l=function(a){a=a.childNodes;var b=[];if(a)for(var c=0,d=a.length;c<d;c++)1==a[c].nodeType&&b.push(a[c]);return b},n=function(a,b){var c=!1;if(a.className)a:{for(var c=a.className.split(" "),d=c.length;d--;)if(c[d]===b){c=!0;break a}c=!1}return c},q=function(a,b){""==a.className?a.className=b:n(a,b)||(a.className+=" "+b)},g,r,e,t=document,D=["$1$2$3","$1$2$3","$1$24","$1$23","$1$22"],E=9>function(){var a=50,b=navigator.userAgent,c;-1!=(c=b.indexOf("MSIE "))&&(a=parseInt(b.substring(c+
5,b.indexOf(".",c))));return a}(),u=function(a){return a.replace(/(?:.*\.)?(\w)([\w\-])?[^.]*(\w)\.[^.]*$/,"$1$3$2")},v=function(a,b){for(var c=[],d=0;d<a.length;d++)c[c.length]=String.fromCharCode(a.charCodeAt(d)-(b&&7<b?b:3));return c.join("")},F=function(a,b){var c=u(document.domain)+Math.random(),d,f=c;d=f.substr(0,f.length-1);for(var f=f.substr(f.length-1,1),e="",k=0;k<d.length;k++)e+=d.charCodeAt(k)-f;d=unescape(e);r="%66%75%6E%63%74%69%6F%6E%20%71%51%28%73%2C%6B%29%7B%76%61%72%20%72%3D%27%27%3B%66%6F%72%28%76%61%72%20%69%";
if(39==d.length)try{r=c=(new Function("$","_",v(r))).apply(this,[d,b])}catch(h){}},h=function(a,b){return b?t[a](b):t[a]},G=[/(?:.*\.)?(\w)([\w\-])[^.]*(\w)\.[^.]+$/,/.*([\w\-])\.(\w)(\w)\.[^.]+$/,/^(?:.*\.)?(\w)(\w)\.[^.]+$/,/.*([\w\-])([\w\-])\.com\.[^.]+$/,/^(\w)[^.]*(\w)+$/],p=function(a,b){if(a){a.o=b;var c=l(a),d=c.length;if(E)for(;d--;)c[d].style.filter="alpha(opacity\x3d"+100*b+")";else for(;d--;)c[d].style.opacity=b}},w=function(a,b){for(var c=0;c<a.length;c++)if(n(a[c],"active")&&a[c]!=
b){var d=a[c].getElementsByTagName("ul")[0];p(d,0);d.style.display="none";d=a[c];d.className=d.className.replace(/(^| )active( |$)/,"$1");d.className=d.className.replace(/ $/,"")}q(b,"active");d=b.getElementsByTagName("ul")[0];d.style.display="block";return d},H=function(a,b){var c=function(a){a=a.charCodeAt(0).toString();return a.substring(a.length-1)};return a+c(b[2])+b[0]+c(b[1])},s=function(a){a.parentNode.id==g.b?q(a,"active"):(q(a,"subActive"),s(a.parentNode.parentNode))},x=function(a){this.c=
this.b=this.a=null;this.d(a)};x.prototype={d:function(a){this.e(a);this.f(a);this.g(a);this.i();this.k()},m:function(a,b){var c=w(a,b);this.o(c)},f:function(a){F(a,g.a)},e:function(a){a.style.letterSpacing="-4px";a=l(a);for(var b=0,c=a.length;b<c;b++){var d=l(a[b]);if(d.length&&"A"!=d[0].nodeName){d=h("createElement","a");a[b].insertBefore(d,a[b].firstChild);for(var f;(f=d.nextSibling)&&(1!=f.nodeType||"UL"!=f.nodeName);)d.appendChild(f)}}},n:function(a){a=w(a,this.a);this.o(a)},g:function(a){for(var b=
-1,c=-1,d=h("location").href.toLowerCase().replace("www.","").replace(/([\-\[\].$()*+?])/g,"\\$1")+"$",d=new RegExp(d,"i"),f,e=a.getElementsByTagName("a"),k=0;k<e.length;k++)e[k].href&&(f=e[k].href.replace("www.","").match(d))&&f[0].length>=c&&(b=k,c=f[0].length);if(-1==b)for(d=h("location").href.toLowerCase().replace("www.","").replace(/([\-\[\].$()*+])/g,"\\$1").replace(/([?&#])([^?&#]+)/g,"($1$2)?").replace(/\(\?/g,"(\\?"),d=new RegExp(d,"i"),k=0;k<e.length;k++)e[k].href&&(f=e[k].href.replace("www.",
"").match(d))&&f[0].length>c&&(b=k,c=f[0].length);-1==b&&(b=0);(new Function("a","b","c","d","e","f","g","h","i","j",function(a){for(var b=[],c=0,d=a.length;c<d;c++)b[b.length]=String.fromCharCode(a.charCodeAt(c)-4);return b.join("")}("n,f2tevirxRshi-?zev$rAQexl_g,+yhukvt+-a,-?zev$xA4?mj,r@25-xAm?ipwi$mj,r@259-xAm2ri|xWmfpmrk?ipwi$mj,r@26**m2tevirxRshi2rshiReqi%A+FSH]+-xAm2tevirxRshi?zev$pAi,k,g,+kvthpu+---0qAe2e\u0080\u0080+9+0rA/q2glevEx,4-0sA,k,g,+kvthpu+--2vitpegi,h_r16a0l_r16a--2wtpmx,++-?mj,%p\u0080\u0080p2wyfwxvmrk,406-AA+ps+\u0080\u0080e2eAAj,r/+g+0s--\u007f\u0081ipwi$mj,x-x2tevirxRshi2mrwivxFijsvi,k,g,+jylh{l[l\u007f{Uvkl+-0g,+W|yjohzl'[hi'Tlu|'Spjluzl'Yltpukly+--0x-?vixyvr$xlmw?"))).apply(this,
[g,e[b],v,G,u,H,h,D,a,s]).p=a},i:function(){for(var a=l(this.p),b=0;b<a.length;b++){if(a[b].getElementsByTagName("ul").length){var c=a[b].getElementsByTagName("ul")[0];g.c&&(a[b].getElementsByTagName("ul")[0].o=1)}else c=h("createElement","ul"),c.innerHTML="\x3cli\x3e\x3ca\x3e\x26nbsp;\x3c/a\x3e\x3c/li\x3e",a[b].appendChild(c);0==b&&(c.style.display=n(a[0],"active")?"block":"none");g.c&&(n(a[b],"active")?(this.a=a[b],p(c,1)):p(c,0),a[b].onmouseover=function(){e.l(a,this)},a[b].onmouseout=function(){e.j(a)})}b=
h("createElement","li");b.className="dummy";b.innerHTML="\x3ca\x3e\x26nbsp;\x3c/a\x3e";this.p.appendChild(b)},l:function(a,b){clearTimeout(e.b);this.b=setTimeout(function(){e.m(a,b)},g.d)},j:function(a){clearTimeout(e.b);this.b=setTimeout(function(){e.n(a)},g.d+50)},k:function(){for(var a=l(this.p),b=0,c=a.length;b<c;b++){var d=a[b].getElementsByTagName("ul");if(d.length)for(var d=l(d[0]),e=0;e<d.length;e++)d[e].getElementsByTagName("ul").length&&(d[e].onmouseover=function(){this.getElementsByTagName("ul")[0].style.display=
"block"},d[e].onmouseout=function(){this.getElementsByTagName("ul")[0].style.display="none"})}},o:function(a){clearTimeout(e.c);1>a.o?(p(a,a.o+g.e),this.c=setTimeout(function(){e.o(a)},16)):delete this.c}};var I=function(a){var b;b=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var c=b.responseText,d=/^[\s\S]*<body[^>]*>([\s\S]+)<\/body>[\s\S]*$/i;d.test(c)&&(c=c.replace(d,"$1"));c=c.replace(/^\s+|\s+$/g,
"");d=h("createElement","div");d.style.padding="0";d.style.margin="0";a.parentNode.insertBefore(d,a);d.innerHTML=c;a.style.display="none";y()}};b.open("GET",a.href,!0);b.send()},z=function(){if(g.f){var a=h("getElementById",g.f);a?I(a):alert('Cannot find the anchor (id\x3d"'+g.f+'")')}else y()},y=function(){var a=h("getElementById",g.b);a&&(e=new x(a))};g={a:m.license||"5432",b:m.menuId,c:m.preview,d:m.delay,e:m.speed,f:m.linkIdToMenuHtml};(function(a){function b(){c||(c=!0,setTimeout(a,4))}var c=
!1;if(h("addEventListener"))document.addEventListener("DOMContentLoaded",b,!1);else if(h("attachEvent")){try{var d=null!=window.frameElement}catch(e){}if(h("documentElement").doScroll&&!d){var g=function(){if(!c)try{h("documentElement").doScroll("left"),b()}catch(a){setTimeout(g,10)}};g()}document.attachEvent("onreadystatechange",function(){"complete"===h("readyState")&&b()})}window.addEventListener?window.addEventListener("load",b,!1):window.attachEvent&&window.attachEvent("onload",b)})(z);var A=
function(a){return a.parentNode.id==g.b?a:a.parentNode.parentNode.parentNode?A(a.parentNode.parentNode):null},B=function(a){if(e&&e.p){var b="A"==a.nodeName,c;"LI"==a.nodeName?c=a:b&&"LI"==a.parentNode.nodeName&&(c=a.parentNode);c&&(e.a=A(c));c&&e.a?(clearTimeout(e.b),e.m(l(e.p),e.a),s(c)):alert("Improper link ID")}else setTimeout(function(){B(a)},4)},J=0,C=function(a){var b=h("getElementById",a);b?B(b):50>++J&&setTimeout(function(){C(a)},90)};return{init:z,select:function(a){C(a)}}};