package com.inkubator.sms.gateway.entity;
// Generated May 9, 2014 9:50:44 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;

/**
 * LoginHistory generated by hbm2java
 */
@Entity
@Indexed
@Table(name = "login_history", catalog = "sms_gateway"
)
public class LoginHistory implements java.io.Serializable {

    private long id;
    private String userName;
    private Date loginDate;
    private Date logOutDate;
    private String ipAddress;
    private String languange;
   

    public LoginHistory() {
    }

    public LoginHistory(long id) {
        this.id = id;
    }

    public LoginHistory(long id, Date loginDate, Date logOutDate, String ipAddress, String languange) {
        this.id = id;

        this.loginDate = loginDate;
        this.logOutDate = logOutDate;
        this.ipAddress = ipAddress;
        this.languange = languange;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LOGIN_DATE", length = 19)
    public Date getLoginDate() {
        return this.loginDate;
    }

    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LOG_OUT_DATE", length = 19)
    public Date getLogOutDate() {
        return this.logOutDate;
    }

    public void setLogOutDate(Date logOutDate) {
        this.logOutDate = logOutDate;
    }

    @Column(name = "IP_ADDRESS", length = 45)
    @Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Column(name = "LANGUANGE", length = 5)
    public String getLanguange() {
        return this.languange;
    }

    public void setLanguange(String languange) {
        this.languange = languange;
    }

    @Column(name = "user_name", length = 45)
    @Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    

}
