package com.inkubator.sms.gateway.entity;
// Generated Nov 3, 2014 9:53:53 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;

/**
 * SmsActivity generated by hbm2java
 */
@Entity
@Indexed
@Table(name = "sms_activity", catalog = "sms_gateway"
)
public class SmsActivity implements java.io.Serializable {

    private long id;
    private Integer version;
    private String fromSms;
    private String destination;
    private Boolean isSchedule;
    private Date sendDate;
    private Date sendTime;
    private String contentSms;
    private Boolean isSend;
    private Double priceSms;

    public SmsActivity() {
    }

    public SmsActivity(long id) {
        this.id = id;
    }

    public SmsActivity(long id, String fromSms, String destination, Boolean isSchedule, Date sendDate, Date sendTime, String contentSms, Boolean isSend) {
        this.id = id;
        this.fromSms = fromSms;
        this.destination = destination;
        this.isSchedule = isSchedule;
        this.sendDate = sendDate;
        this.sendTime = sendTime;
        this.contentSms = contentSms;
        this.isSend = isSend;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "from_sms", length = 45)
    @Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
    public String getFromSms() {
        return this.fromSms;
    }

    public void setFromSms(String fromSms) {
        this.fromSms = fromSms;
    }

    @Column(name = "destination", length = 45)
    @Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    @Column(name = "is_schedule")
    public Boolean getIsSchedule() {
        return this.isSchedule;
    }

    public void setIsSchedule(Boolean isSchedule) {
        this.isSchedule = isSchedule;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "send_date", length = 10)
    @Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
    public Date getSendDate() {
        return this.sendDate;
    }

    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "send_time", length = 8)
    public Date getSendTime() {
        return this.sendTime;
    }

    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    @Column(name = "content_sms", length = 65535)
    public String getContentSms() {
        return this.contentSms;
    }

    public void setContentSms(String contentSms) {
        this.contentSms = contentSms;
    }

    @Column(name = "is_send")
    public Boolean getIsSend() {
        return this.isSend;
    }

    public void setIsSend(Boolean isSend) {
        this.isSend = isSend;
    }

    @Column(name = "price_sms", precision = 22, scale = 0)
    public Double getPriceSms() {
        return priceSms;
    }

    public void setPriceSms(Double priceSms) {
        this.priceSms = priceSms;
    }

}
