package com.inkubator.hrm.entity;
// Generated Aug 20, 2014 9:17:56 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * AdmonitionType generated by hbm2java
 */
@Entity
@Table(name="admonition_type"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class AdmonitionType  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private String code;
     private String name;
     private String description;
     private Integer longTerm;
     private Integer suspend;
     private Double salaryCut;

    public AdmonitionType() {
    }

	
    public AdmonitionType(long id) {
        this.id = id;
    }
    public AdmonitionType(long id, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String code, String name, String description, Integer longTerm, Integer suspend, Double salaryCut) {
       this.id = id;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.code = code;
       this.name = name;
       this.description = description;
       this.longTerm = longTerm;
       this.suspend = suspend;
       this.salaryCut = salaryCut;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="code", unique=true, length=8)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535, columnDefinition="Text")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="long_term")
    public Integer getLongTerm() {
        return this.longTerm;
    }
    
    public void setLongTerm(Integer longTerm) {
        this.longTerm = longTerm;
    }

    
    @Column(name="suspend")
    public Integer getSuspend() {
        return this.suspend;
    }
    
    public void setSuspend(Integer suspend) {
        this.suspend = suspend;
    }

    
    @Column(name="salary_cut", precision=22, scale=0)
    public Double getSalaryCut() {
        return this.salaryCut;
    }
    
    public void setSalaryCut(Double salaryCut) {
        this.salaryCut = salaryCut;
    }




}


