package com.inkubator.hrm.entity;
// Generated Apr 2, 2015 2:03:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Announcement generated by hbm2java
 */
@Entity
@Table(name = "announcement", catalog = "hrm"
)
public class Announcement implements java.io.Serializable {

    private long id;
    private Integer version;
    private Company company;
    private String subject;
    private String announcementContent;
    private Integer timeModel;
    private Date periodeStartDate;
    private Date periodeEndDate;
    private int viewModel;
    private boolean internetPublish;
    private String attachmentPath;
    private Boolean emailIsSend;
    private Date createdOn;
    private String createdBy;
    private String updatedBy;
    private String nomor;
    private Date updatedOn;
    private Boolean isAlreadyShow;
    private Set<AnnouncementGoljab> announcementGoljabs = new HashSet<AnnouncementGoljab>(0);
    private Set<AnnouncementUnit> announcementUnits = new HashSet<AnnouncementUnit>(0);
    private Set<AnnouncementEmpType> announcementEmpTypes = new HashSet<AnnouncementEmpType>(0);

    public Announcement() {
    }

    public Announcement(long id, Company company, String subject, int viewModel, boolean internetPublish) {
        this.id = id;
        this.company = company;
        this.subject = subject;
        this.viewModel = viewModel;
        this.internetPublish = internetPublish;
    }

    public Announcement(long id, Company company, String subject, String announcementContent, Integer timeModel, Date periodeStartDate, Date periodeEndDate, int viewModel, boolean internetPublish, String attachmentPath, Boolean emailIsSend, Date createdOn, String createdBy, String updatedBy, Date updatedOn, Boolean isAlreadyShow, Set<AnnouncementGoljab> announcementGoljabs, Set<AnnouncementUnit> announcementUnits, Set<AnnouncementEmpType> announcementEmpTypes) {
        this.id = id;
        this.company = company;
        this.subject = subject;
        this.announcementContent = announcementContent;
        this.timeModel = timeModel;
        this.periodeStartDate = periodeStartDate;
        this.periodeEndDate = periodeEndDate;
        this.viewModel = viewModel;
        this.internetPublish = internetPublish;
        this.attachmentPath = attachmentPath;
        this.emailIsSend = emailIsSend;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
        this.isAlreadyShow = isAlreadyShow;
        this.announcementGoljabs = announcementGoljabs;
        this.announcementUnits = announcementUnits;
        this.announcementEmpTypes = announcementEmpTypes;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id", nullable = false)
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    @Column(name = "subject", nullable = false)
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Column(name = "announcement_content", length = 65535, columnDefinition="Text")
    public String getAnnouncementContent() {
        return this.announcementContent;
    }

    public void setAnnouncementContent(String announcementContent) {
        this.announcementContent = announcementContent;
    }

    @Column(name = "time_model")
    public Integer getTimeModel() {
        return this.timeModel;
    }

    public void setTimeModel(Integer timeModel) {
        this.timeModel = timeModel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "periode_start_date", length = 10)
    public Date getPeriodeStartDate() {
        return this.periodeStartDate;
    }

    public void setPeriodeStartDate(Date periodeStartDate) {
        this.periodeStartDate = periodeStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "periode_end_date", length = 10)
    public Date getPeriodeEndDate() {
        return this.periodeEndDate;
    }

    public void setPeriodeEndDate(Date periodeEndDate) {
        this.periodeEndDate = periodeEndDate;
    }

    @Column(name = "view_model", nullable = false)
    public int getViewModel() {
        return this.viewModel;
    }

    public void setViewModel(int viewModel) {
        this.viewModel = viewModel;
    }

    @Column(name = "internet_publish", nullable = false)
    public boolean getInternetPublish() {
        return this.internetPublish;
    }

    public void setInternetPublish(boolean internetPublish) {
        this.internetPublish = internetPublish;
    }

    @Column(name="nomor", unique=true, length = 45)
    public String getNomor() {
        return nomor;
    }

    public void setNomor(String nomor) {
        this.nomor = nomor;
    }
    
    @Column(name = "attachment_path", length = 200)
    public String getAttachmentPath() {
        return this.attachmentPath;
    }

    public void setAttachmentPath(String attachmentPath) {
        this.attachmentPath = attachmentPath;
    }

    @Column(name = "email_is_send")
    public Boolean getEmailIsSend() {
        return this.emailIsSend;
    }

    public void setEmailIsSend(Boolean emailIsSend) {
        this.emailIsSend = emailIsSend;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Column(name = "is_already_show")
    public Boolean getIsAlreadyShow() {
        return this.isAlreadyShow;
    }

    public void setIsAlreadyShow(Boolean isAlreadyShow) {
        this.isAlreadyShow = isAlreadyShow;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "announcement")
    public Set<AnnouncementGoljab> getAnnouncementGoljabs() {
        return this.announcementGoljabs;
    }

    public void setAnnouncementGoljabs(Set<AnnouncementGoljab> announcementGoljabs) {
        this.announcementGoljabs = announcementGoljabs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "announcement")
    public Set<AnnouncementUnit> getAnnouncementUnits() {
        return this.announcementUnits;
    }

    public void setAnnouncementUnits(Set<AnnouncementUnit> announcementUnits) {
        this.announcementUnits = announcementUnits;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "announcement")
    public Set<AnnouncementEmpType> getAnnouncementEmpTypes() {
        return this.announcementEmpTypes;
    }

    public void setAnnouncementEmpTypes(Set<AnnouncementEmpType> announcementEmpTypes) {
        this.announcementEmpTypes = announcementEmpTypes;
    }

}
