package com.inkubator.hrm.entity;
// Generated Apr 2, 2015 2:03:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnnouncementEmpTypeId generated by hbm2java
 */
@Embeddable
public class AnnouncementEmpTypeId  implements java.io.Serializable {


     private long announcementId;
     private long employeeTypeId;

    public AnnouncementEmpTypeId() {
    }

    public AnnouncementEmpTypeId(long announcementId, long employeeTypeId) {
       this.announcementId = announcementId;
       this.employeeTypeId = employeeTypeId;
    }
   


    @Column(name="announcement_id", nullable=false)
    public long getAnnouncementId() {
        return this.announcementId;
    }
    
    public void setAnnouncementId(long announcementId) {
        this.announcementId = announcementId;
    }


    @Column(name="employee_type_id", nullable=false)
    public long getEmployeeTypeId() {
        return this.employeeTypeId;
    }
    
    public void setEmployeeTypeId(long employeeTypeId) {
        this.employeeTypeId = employeeTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnnouncementEmpTypeId) ) return false;
		 AnnouncementEmpTypeId castOther = ( AnnouncementEmpTypeId ) other; 
         
		 return (this.getAnnouncementId()==castOther.getAnnouncementId())
 && (this.getEmployeeTypeId()==castOther.getEmployeeTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAnnouncementId();
         result = 37 * result + (int) this.getEmployeeTypeId();
         return result;
   }   


}


