package com.inkubator.hrm.entity;
// Generated Apr 2, 2015 2:03:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * AnnouncementGoljab generated by hbm2java
 */
@Entity
@Table(name="announcement_goljab"
    ,catalog="hrm"
)
public class AnnouncementGoljab  implements java.io.Serializable {


     private AnnouncementGoljabId id;
     private Integer version;
     private Announcement announcement;
     private GolonganJabatan golonganJabatan;
     private Date createdOn;
     private String createdBy;

    public AnnouncementGoljab() {
    }

	
    public AnnouncementGoljab(AnnouncementGoljabId id, Announcement announcement, GolonganJabatan golonganJabatan) {
        this.id = id;
        this.announcement = announcement;
        this.golonganJabatan = golonganJabatan;
    }
    public AnnouncementGoljab(AnnouncementGoljabId id, Announcement announcement, GolonganJabatan golonganJabatan, Date createdOn, String createdBy) {
       this.id = id;
       this.announcement = announcement;
       this.golonganJabatan = golonganJabatan;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="announcementId", column=@Column(name="announcement_id", nullable=false) ), 
        @AttributeOverride(name="golonganJabatanId", column=@Column(name="golongan_jabatan_id", nullable=false) ) } )
    public AnnouncementGoljabId getId() {
        return this.id;
    }
    
    public void setId(AnnouncementGoljabId id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="announcement_id", nullable=false, insertable=false, updatable=false)
    public Announcement getAnnouncement() {
        return this.announcement;
    }
    
    public void setAnnouncement(Announcement announcement) {
        this.announcement = announcement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="golongan_jabatan_id", nullable=false, insertable=false, updatable=false)
    public GolonganJabatan getGolonganJabatan() {
        return this.golonganJabatan;
    }
    
    public void setGolonganJabatan(GolonganJabatan golonganJabatan) {
        this.golonganJabatan = golonganJabatan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


