package com.inkubator.hrm.entity;
// Generated Jun 16, 2014 8:44:01 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApplicantSpecListId generated by hbm2java
 */
@Embeddable
public class ApplicantSpecListId  implements java.io.Serializable {


     private long applicantId;
     private long orgTypeOfSpecListId;

    public ApplicantSpecListId() {
    }

    public ApplicantSpecListId(long applicantId, long orgTypeOfSpecListId) {
       this.applicantId = applicantId;
       this.orgTypeOfSpecListId = orgTypeOfSpecListId;
    }    
    
    @Column(name="applicant_id", nullable=false)
    public long getApplicantId() {
		return applicantId;
	}

	public void setApplicantId(long applicantId) {
		this.applicantId = applicantId;
	}

	@Column(name="org_type_of_spec_list_id", nullable=false)
	public long getOrgTypeOfSpecListId() {
		return orgTypeOfSpecListId;
	}

	public void setOrgTypeOfSpecListId(long orgTypeOfSpecListId) {
		this.orgTypeOfSpecListId = orgTypeOfSpecListId;
	}	
	
   public boolean equals(Object other) {
         if ((this == other )) return true;
		 if ((other == null )) return false;
		 if (!(other instanceof ApplicantSpecListId)) return false;
		 ApplicantSpecListId castOther = ( ApplicantSpecListId ) other; 
         
		 return (this.getApplicantId()==castOther.getApplicantId()) && (this.getOrgTypeOfSpecListId()==castOther.getOrgTypeOfSpecListId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getApplicantId();
         result = 37 * result + (int) this.getOrgTypeOfSpecListId();
         return result;
   }   


}


