package com.inkubator.hrm.entity;
// Generated Jan 14, 2016 1:59:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * AppraisalProgramEmpAssesor generated by hbm2java
 */
@Entity
@Table(name="appraisal_program_emp_assesor"
    ,catalog="hrm"
)
public class AppraisalProgramEmpAssesor  implements java.io.Serializable {


     private long id;
     private Integer version;
     private AppraisalProgram appraisalProgram;
     private EmpData empDataByEmpId;
     private EmpData empDataByAssesorEmpId;
     private Integer scala;
     private String createdBy;
     private Date createdOn;

    public AppraisalProgramEmpAssesor() {
    }

	
    public AppraisalProgramEmpAssesor(long id) {
        this.id = id;
    }
    public AppraisalProgramEmpAssesor(long id, AppraisalProgram appraisalProgram, EmpData empDataByEmpId, EmpData empDataByAssesorEmpId, Integer scala, String createdBy, Date createdOn) {
       this.id = id;
       this.appraisalProgram = appraisalProgram;
       this.empDataByEmpId = empDataByEmpId;
       this.empDataByAssesorEmpId = empDataByAssesorEmpId;
       this.scala = scala;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="appraisal_program_id")
    public AppraisalProgram getAppraisalProgram() {
        return this.appraisalProgram;
    }
    
    public void setAppraisalProgram(AppraisalProgram appraisalProgram) {
        this.appraisalProgram = appraisalProgram;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_id")
    public EmpData getEmpDataByEmpId() {
        return this.empDataByEmpId;
    }
    
    public void setEmpDataByEmpId(EmpData empDataByEmpId) {
        this.empDataByEmpId = empDataByEmpId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="assesor_emp_id")
    public EmpData getEmpDataByAssesorEmpId() {
        return this.empDataByAssesorEmpId;
    }
    
    public void setEmpDataByAssesorEmpId(EmpData empDataByAssesorEmpId) {
        this.empDataByAssesorEmpId = empDataByAssesorEmpId;
    }

    
    @Column(name="scala")
    public Integer getScala() {
        return this.scala;
    }
    
    public void setScala(Integer scala) {
        this.scala = scala;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }




}


