package com.inkubator.hrm.entity;
// Generated Jun 16, 2014 8:44:01 PM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * HrmMenuRole generated by hbm2java
 */
@Entity
@Table(name = "appraisal_program_emp", catalog = "hrm"
)
public class AppraisalProgramEmp implements java.io.Serializable {

    private AppraisalProgramEmpId id;
    private AppraisalProgram appraisalProgram;
    private EmpData empData;
    private String createdBy;
    private Date createdOn;
    private Long totalAssesor;

    public AppraisalProgramEmp() {
    }

    public AppraisalProgramEmp(AppraisalProgramEmpId id, AppraisalProgram appraisalProgram, EmpData empData) {
        this.id = id;
        this.appraisalProgram = appraisalProgram;
        this.empData = empData;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "appraisalProgramId", column = @Column(name = "appraisal_program_id", nullable = false)),
        @AttributeOverride(name = "empDataId", column = @Column(name = "emp_data_id", nullable = false))})
    public AppraisalProgramEmpId getId() {
        return this.id;
    }

    public void setId(AppraisalProgramEmpId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appraisal_program_id", nullable = false, insertable = false, updatable = false)
    public AppraisalProgram getAppraisalProgram() {
        return appraisalProgram;
    }

    public void setAppraisalProgram(AppraisalProgram appraisalProgram) {
        this.appraisalProgram = appraisalProgram;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_data_id", nullable = false, insertable = false, updatable = false)
    public EmpData getEmpData() {
        return empData;
    }

    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Transient
    public Long getTotalAssesor() {
        return totalAssesor;
    }

    public void setTotalAssesor(Long totalAssesor) {
        this.totalAssesor = totalAssesor;
    }

}
