package com.inkubator.hrm.entity;
// Generated Dec 3, 2015 10:26:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * AppraisalCompetencyType generated by hbm2java
 */
@Entity
@Table(name="appraisal_competency_type"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class AppraisalCompetencyType  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String code;
     private String name;
     private String description;
     private String createdBy;
     private String updatedBy;
     private Date createdOn;
     private Date updatedOn;
     private Byte visibility;
     private Set<AppraisalCompetencyTypeGolJab> appraisalCompetencyTypeGolJabs = new HashSet<AppraisalCompetencyTypeGolJab>(0);

    public AppraisalCompetencyType() {
    }

	
    public AppraisalCompetencyType(long id, String code) {
        this.id = id;
        this.code = code;
    }
    public AppraisalCompetencyType(long id, String code, String name, String description, String createdBy, String updatedBy, Date createdOn, Date updatedOn, Byte visibility, Set<AppraisalCompetencyTypeGolJab> appraisalCompetencyTypeGolJabs) {
       this.id = id;
       this.code = code;
       this.name = name;
       this.description = description;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.visibility = visibility;
       this.appraisalCompetencyTypeGolJabs = appraisalCompetencyTypeGolJabs;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="code", unique=true, nullable=false, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="visibility")
    public Byte getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(Byte visibility) {
        this.visibility = visibility;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="appraisalCompetencyType")
    public Set<AppraisalCompetencyTypeGolJab> getAppraisalCompetencyTypeGolJabs() {
        return this.appraisalCompetencyTypeGolJabs;
    }
    
    public void setAppraisalCompetencyTypeGolJabs(Set<AppraisalCompetencyTypeGolJab> appraisalCompetencyTypeGolJabs) {
        this.appraisalCompetencyTypeGolJabs = appraisalCompetencyTypeGolJabs;
    }




}


