package com.inkubator.hrm.entity;
// Generated Oct 7, 2014 2:27:51 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApprovalDefinitionOverTime generated by hbm2java
 */
@Entity
@Table(name="approval_definition_over_time"
    ,catalog="hrm_personalia"
)
public class ApprovalDefinitionOT  implements java.io.Serializable {


     private ApprovalDefinitionOTId id;
     private ApprovalDefinition approvalDefinition;
     private WtOverTime wtOverTime;
     private String description;

    public ApprovalDefinitionOT() {
    }

	
    public ApprovalDefinitionOT(ApprovalDefinitionOTId id, ApprovalDefinition approvalDefinition, WtOverTime wtOverTime) {
        this.id = id;
        this.approvalDefinition = approvalDefinition;
        this.wtOverTime = wtOverTime;
    }
    public ApprovalDefinitionOT(ApprovalDefinitionOTId id, ApprovalDefinition approvalDefinition, WtOverTime wtOverTime, String description) {
       this.id = id;
       this.approvalDefinition = approvalDefinition;
       this.wtOverTime = wtOverTime;
       this.description = description;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="approvalDefinitionId", column=@Column(name="approval_definition_id", nullable=false) ), 
        @AttributeOverride(name="overTimeId", column=@Column(name="over_time_id", nullable=false) ) } )
    public ApprovalDefinitionOTId getId() {
        return this.id;
    }
    
    public void setId(ApprovalDefinitionOTId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="approval_definition_id", nullable=false, insertable=false, updatable=false)
    public ApprovalDefinition getApprovalDefinition() {
        return this.approvalDefinition;
    }
    
    public void setApprovalDefinition(ApprovalDefinition approvalDefinition) {
        this.approvalDefinition = approvalDefinition;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="over_time_id", nullable=false, insertable=false, updatable=false)
    public WtOverTime getWtOverTime() {
        return this.wtOverTime;
    }
    
    public void setWtOverTime(WtOverTime wtOverTime) {
        this.wtOverTime = wtOverTime;
    }
    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


