package com.inkubator.hrm.entity;
// Generated Mar 26, 2015 1:07:27 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApprovalDefinitionLoanSchema generated by hbm2java
 */
@Entity
@Table(name="approval_definition_loan_schema"
    ,catalog="hrm"
)
public class ApprovalDefinitionLoanSchema  implements java.io.Serializable {


     private ApprovalDefinitionLoanSchemaId id;
     private ApprovalDefinition approvalDefinition;
     private LoanNewSchema loanNewSchema;
     private String description;

    public ApprovalDefinitionLoanSchema() {
    }

	
    public ApprovalDefinitionLoanSchema(ApprovalDefinitionLoanSchemaId id, ApprovalDefinition approvalDefinition, LoanNewSchema loanNewSchema) {
        this.id = id;
        this.approvalDefinition = approvalDefinition;
        this.loanNewSchema = loanNewSchema;
    }
    public ApprovalDefinitionLoanSchema(ApprovalDefinitionLoanSchemaId id, ApprovalDefinition approvalDefinition, LoanNewSchema loanNewSchema, String description) {
       this.id = id;
       this.approvalDefinition = approvalDefinition;
       this.loanNewSchema = loanNewSchema;
       this.description = description;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="approvalDefinitionLoanId", column=@Column(name="approval_definition_loan_id", nullable=false) ), 
        @AttributeOverride(name="loanNewSchemaId", column=@Column(name="loan_new_schema_id", nullable=false) ) } )
    public ApprovalDefinitionLoanSchemaId getId() {
        return this.id;
    }
    
    public void setId(ApprovalDefinitionLoanSchemaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="approval_definition_loan_id", nullable=false, insertable=false, updatable=false)
    public ApprovalDefinition getApprovalDefinition() {
        return this.approvalDefinition;
    }
    
    public void setApprovalDefinition(ApprovalDefinition approvalDefinition) {
        this.approvalDefinition = approvalDefinition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loan_new_schema_id", nullable=false, insertable=false, updatable=false)
    public LoanNewSchema getLoanNewSchema() {
        return this.loanNewSchema;
    }
    
    public void setLoanNewSchema(LoanNewSchema loanNewSchema) {
        this.loanNewSchema = loanNewSchema;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


