package com.inkubator.hrm.entity;
// Generated Dec 3, 2015 10:26:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppraisalCompetencyTypeGolJab generated by hbm2java
 */
@Entity
@Table(name="appraisal_competency_type_gol_jab"
    ,catalog="hrm"
)
public class AppraisalCompetencyTypeGolJab  implements java.io.Serializable {


     private AppraisalCompetencyTypeGolJabId id;
     private AppraisalCompetencyType appraisalCompetencyType;
     private GolonganJabatan golonganJabatan;
     private Date createdOn;
     private String createdBy;

    public AppraisalCompetencyTypeGolJab() {
    }

	
    public AppraisalCompetencyTypeGolJab(AppraisalCompetencyTypeGolJabId id, AppraisalCompetencyType appraisalCompetencyType, GolonganJabatan golonganJabatan) {
        this.id = id;
        this.appraisalCompetencyType = appraisalCompetencyType;
        this.golonganJabatan = golonganJabatan;
    }
    public AppraisalCompetencyTypeGolJab(AppraisalCompetencyTypeGolJabId id, AppraisalCompetencyType appraisalCompetencyType, GolonganJabatan golonganJabatan, Date createdOn, String createdBy) {
       this.id = id;
       this.appraisalCompetencyType = appraisalCompetencyType;
       this.golonganJabatan = golonganJabatan;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="competencyTypeId", column=@Column(name="competency_type_id", nullable=false) ), 
        @AttributeOverride(name="golJabId", column=@Column(name="gol_jab_id", nullable=false) ) } )
    public AppraisalCompetencyTypeGolJabId getId() {
        return this.id;
    }
    
    public void setId(AppraisalCompetencyTypeGolJabId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="competency_type_id", nullable=false, insertable=false, updatable=false)
    public AppraisalCompetencyType getAppraisalCompetencyType() {
        return this.appraisalCompetencyType;
    }
    
    public void setAppraisalCompetencyType(AppraisalCompetencyType appraisalCompetencyType) {
        this.appraisalCompetencyType = appraisalCompetencyType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gol_jab_id", nullable=false, insertable=false, updatable=false)
    public GolonganJabatan getGolonganJabatan() {
        return this.golonganJabatan;
    }
    
    public void setGolonganJabatan(GolonganJabatan golonganJabatan) {
        this.golonganJabatan = golonganJabatan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


