package com.inkubator.hrm.entity;
// Generated Jun 16, 2014 8:44:01 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LeaveApprovalDefinitionId generated by hbm2java
 */
@Embeddable
public class AppraisalProgramEmpId  implements java.io.Serializable {


	private long appraisalProgramId;
    private long empDataId;

    public AppraisalProgramEmpId() {
    	
    }

    public AppraisalProgramEmpId(long appraisalProgramId, long empDataId) {
       this.appraisalProgramId = appraisalProgramId;
       this.empDataId = empDataId;
    }
    
    @Column(name="appraisal_program_id", nullable=false)
    public long getAppraisalProgramId() {
		return appraisalProgramId;
	}

	public void setAppraisalProgramId(long appraisalProgramId) {
		this.appraisalProgramId = appraisalProgramId;
	}

	@Column(name="emp_data_id", nullable=false)
	public long getEmpDataId() {
		return empDataId;
	}

	public void setEmpDataId(long empDataId) {
		this.empDataId = empDataId;
	}
	
	public boolean equals(Object other) {
		if ((this == other )) return true;
		if ((other == null )) return false;
		if (!(other instanceof AppraisalProgramEmpId)) return false;
		AppraisalProgramEmpId castOther = ( AppraisalProgramEmpId ) other; 
        
		return (this.getAppraisalProgramId()==castOther.getAppraisalProgramId()) && (this.getEmpDataId()==castOther.getEmpDataId());
	}
   
	public int hashCode() {
        int result = 17;
        
        result = 37 * result + (int) this.getAppraisalProgramId();
        result = 37 * result + (int) this.getEmpDataId();
        return result;
   	}   
}