package com.inkubator.hrm.entity;
// Generated Mar 26, 2015 1:07:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApprovalDefinitionLoanSchemaId generated by hbm2java
 */
@Embeddable
public class ApprovalDefinitionLoanSchemaId  implements java.io.Serializable {


     private long approvalDefinitionLoanId;
     private long loanNewSchemaId;

    public ApprovalDefinitionLoanSchemaId() {
    }

    public ApprovalDefinitionLoanSchemaId(long approvalDefinitionLoanId, long loanNewSchemaId) {
       this.approvalDefinitionLoanId = approvalDefinitionLoanId;
       this.loanNewSchemaId = loanNewSchemaId;
    }
   


    @Column(name="approval_definition_loan_id", nullable=false)
    public long getApprovalDefinitionLoanId() {
        return this.approvalDefinitionLoanId;
    }
    
    public void setApprovalDefinitionLoanId(long approvalDefinitionLoanId) {
        this.approvalDefinitionLoanId = approvalDefinitionLoanId;
    }


    @Column(name="loan_new_schema_id", nullable=false)
    public long getLoanNewSchemaId() {
        return this.loanNewSchemaId;
    }
    
    public void setLoanNewSchemaId(long loanNewSchemaId) {
        this.loanNewSchemaId = loanNewSchemaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ApprovalDefinitionLoanSchemaId) ) return false;
		 ApprovalDefinitionLoanSchemaId castOther = ( ApprovalDefinitionLoanSchemaId ) other; 
         
		 return (this.getApprovalDefinitionLoanId()==castOther.getApprovalDefinitionLoanId())
 && (this.getLoanNewSchemaId()==castOther.getLoanNewSchemaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getApprovalDefinitionLoanId();
         result = 37 * result + (int) this.getLoanNewSchemaId();
         return result;
   }   


}


