package com.inkubator.hrm.entity;
// Generated Dec 3, 2015 10:26:30 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppraisalCompetencyTypeGolJabId generated by hbm2java
 */
@Embeddable
public class AppraisalCompetencyTypeGolJabId  implements java.io.Serializable {


     private long competencyTypeId;
     private long golJabId;

    public AppraisalCompetencyTypeGolJabId() {
    }

    public AppraisalCompetencyTypeGolJabId(long competencyTypeId, long golJabId) {
       this.competencyTypeId = competencyTypeId;
       this.golJabId = golJabId;
    }
   


    @Column(name="competency_type_id", nullable=false)
    public long getCompetencyTypeId() {
        return this.competencyTypeId;
    }
    
    public void setCompetencyTypeId(long competencyTypeId) {
        this.competencyTypeId = competencyTypeId;
    }


    @Column(name="gol_jab_id", nullable=false)
    public long getGolJabId() {
        return this.golJabId;
    }
    
    public void setGolJabId(long golJabId) {
        this.golJabId = golJabId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppraisalCompetencyTypeGolJabId) ) return false;
		 AppraisalCompetencyTypeGolJabId castOther = ( AppraisalCompetencyTypeGolJabId ) other; 
         
		 return (this.getCompetencyTypeId()==castOther.getCompetencyTypeId())
 && (this.getGolJabId()==castOther.getGolJabId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCompetencyTypeId();
         result = 37 * result + (int) this.getGolJabId();
         return result;
   }   


}


