package com.inkubator.hrm.entity;
// Generated May 26, 2014 1:36:05 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * AttendanceStatus generated by hbm2java
 */
@Entity
@Table(name="attendance_status"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class AttendanceStatus  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String code;
     private String statusKehadrian;
     private String description;
     private Integer isPresent;
     private Integer isPay;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date upatedOn;
     private Set<Leave> leaves = new HashSet<Leave>(0);

    public AttendanceStatus() {
    }

	
    public AttendanceStatus(long id) {
        this.id = id;
    }
    public AttendanceStatus(long id, String code, String statusKehadrian, String description, Integer isPresent, Integer isPay, String createdBy, Date createdOn, String updatedBy, Date upatedOn) {
       this.id = id;
       this.code = code;
       this.statusKehadrian = statusKehadrian;
       this.description = description;
       this.isPresent = isPresent;
       this.isPay = isPay;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.upatedOn = upatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="code", unique=true, length=8)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="status_kehadrian", length=60)
    public String getStatusKehadrian() {
        return this.statusKehadrian;
    }
    
    public void setStatusKehadrian(String statusKehadrian) {
        this.statusKehadrian = statusKehadrian;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="is_present")
    public Integer getIsPresent() {
        return this.isPresent;
    }
    
    public void setIsPresent(Integer isPresent) {
        this.isPresent = isPresent;
    }

    
    @Column(name="is_pay")
    public Integer getIsPay() {
        return this.isPay;
    }
    
    public void setIsPay(Integer isPay) {
        this.isPay = isPay;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="upated_on", length=19)
    public Date getUpatedOn() {
        return this.upatedOn;
    }
    
    public void setUpatedOn(Date upatedOn) {
        this.upatedOn = upatedOn;
    }

  @Transient
    public String getIsPayAsLabel() {
        if (isPay == 1) {
            return "Y";
        }

        if (isPay == 0) {
            return "N";
        }
        return null;
    }
    
     @Transient
    public String getIsPresentAsLabel() {
        if (isPresent == 1) {
            return "Y";
        }

        if (isPresent == 0) {
            return "N";
        }
        return null;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attendanceStatus")
	public Set<Leave> getLeaves() {
		return leaves;
	}


	public void setLeaves(Set<Leave> leaves) {
		this.leaves = leaves;
	}


}


