package com.inkubator.hrm.entity;
// Generated Jun 16, 2014 10:20:21 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="bank"
    ,catalog="hrm_payroll"
    , uniqueConstraints = {@UniqueConstraint(columnNames="bank_code"), @UniqueConstraint(columnNames="swift_code"), @UniqueConstraint(columnNames="bank_identification_no"), @UniqueConstraint(columnNames="branch_code")} 
)
public class Bank  implements java.io.Serializable {


     private Long id;
     private Integer version;
     private Bank bank;
     private BankGroup bankGroup;
     private String bankCode;
     private String bankName;
     private String createdBy;
     private Date createdOn;
     private String description;
     private String updatedBy;
     private Date updatedOn;
     private String bankIdentificationNo;
     private String iban;
     private String swiftCode;
     private String address;
     private String bankFax;
     private String bankPhone;
     private String branchCode;
     private String branchName;
     private Set<Bank> banks = new HashSet<Bank>(0);
     private Boolean renderedParent;
     private Boolean renderedChild;

    public Bank() {
    }

	
    public Bank(long id) {
        this.id = id;
    }
    public Bank(long id, Bank bank, BankGroup bankGroup, String bankCode, String bankName, String createdBy, Date createdOn, String description, String updatedBy, Date updatedOn, String bankIdentificationNo, String iban, String swiftCode, String address, String bankFax, String bankPhone, String branchCode, String branchName, Set<Bank> banks) {
       this.id = id;
       this.bank = bank;
       this.bankGroup = bankGroup;
       this.bankCode = bankCode;
       this.bankName = bankName;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.description = description;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.bankIdentificationNo = bankIdentificationNo;
       this.iban = iban;
       this.swiftCode = swiftCode;
       this.address = address;
       this.bankFax = bankFax;
       this.bankPhone = bankPhone;
       this.branchCode = branchCode;
       this.branchName = branchName;
       this.banks = banks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bank_group_id")
    public BankGroup getBankGroup() {
        return this.bankGroup;
    }
    
    public void setBankGroup(BankGroup bankGroup) {
        this.bankGroup = bankGroup;
    }

    
    @Column(name="bank_code", unique=true, length=8)
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    
    @Column(name="bank_name", length=60)
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="bank_identification_no", unique=true, length=32)
    public String getBankIdentificationNo() {
        return this.bankIdentificationNo;
    }
    
    public void setBankIdentificationNo(String bankIdentificationNo) {
        this.bankIdentificationNo = bankIdentificationNo;
    }

    
    @Column(name="iban", length=20)
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }

    
    @Column(name="swift_code", unique=true, length=32)
    public String getSwiftCode() {
        return this.swiftCode;
    }
    
    public void setSwiftCode(String swiftCode) {
        this.swiftCode = swiftCode;
    }

    
    @Column(name="address", length=225)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="bank_fax", length=20)
    public String getBankFax() {
        return this.bankFax;
    }
    
    public void setBankFax(String bankFax) {
        this.bankFax = bankFax;
    }
    
    @Column(name="bank_phone", length=20)
    public String getBankPhone() {
        return this.bankPhone;
    }
    
    public void setBankPhone(String bankPhone) {
        this.bankPhone = bankPhone;
    }

    
    @Column(name="branch_code", unique=true, length=8)
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    
    @Column(name="branch_name", length=60)
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bank")
    public Set<Bank> getBanks() {
        return this.banks;
    }
    
    public void setBanks(Set<Bank> banks) {
        this.banks = banks;
    }

    @Transient
    public Boolean getRenderedParent() {
        if(bank != null){
            renderedParent = Boolean.FALSE;
        }else{    
            renderedParent = Boolean.TRUE;
        }
        return renderedParent;
    }

    public void setRenderedParent(Boolean renderedParent) {
        this.renderedParent = renderedParent;
    }

    @Transient
    public Boolean getRenderedChild() {
        if(bank != null){
            renderedChild = Boolean.TRUE;
        }else{    
            renderedChild = Boolean.FALSE;
        }
        return renderedChild;
    }

    public void setRenderedChild(Boolean renderedChild) {
        this.renderedChild = renderedChild;
    }

    @Transient
    public void getParentOrChild(){
        if(bank != null){
            renderedChild = Boolean.TRUE;
            renderedParent = Boolean.FALSE;
        }else{    
            renderedChild = Boolean.FALSE;
            renderedParent = Boolean.TRUE;
        }
    }


}


