package com.inkubator.hrm.entity;
// Generated Dec 8, 2014 1:55:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * BatchJobExecution generated by hbm2java
 */
@Entity
@Table(name="batch_job_execution"
    ,catalog="hrm"
)
public class BatchJobExecution  implements java.io.Serializable {


     private long jobExecutionId;
     private Long version;
     private BatchJobInstance batchJobInstance;
     private Date createTime;
     private Date startTime;
     private Date endTime;
     private String status;
     private String exitCode;
     private String exitMessage;
     private Date lastUpdated;

    public BatchJobExecution() {
    }

	
    public BatchJobExecution(long jobExecutionId, BatchJobInstance batchJobInstance, Date createTime) {
        this.jobExecutionId = jobExecutionId;
        this.batchJobInstance = batchJobInstance;
        this.createTime = createTime;
    }
    public BatchJobExecution(long jobExecutionId, BatchJobInstance batchJobInstance, Date createTime, Date startTime, Date endTime, String status, String exitCode, String exitMessage, Date lastUpdated) {
       this.jobExecutionId = jobExecutionId;
       this.batchJobInstance = batchJobInstance;
       this.createTime = createTime;
       this.startTime = startTime;
       this.endTime = endTime;
       this.status = status;
       this.exitCode = exitCode;
       this.exitMessage = exitMessage;
       this.lastUpdated = lastUpdated;
    }
   
     @Id 

    
    @Column(name="JOB_EXECUTION_ID", unique=true, nullable=false)
    public long getJobExecutionId() {
        return this.jobExecutionId;
    }
    
    public void setJobExecutionId(long jobExecutionId) {
        this.jobExecutionId = jobExecutionId;
    }

    @Version
    @Column(name="VERSION")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOB_INSTANCE_ID", nullable=false)
    public BatchJobInstance getBatchJobInstance() {
        return this.batchJobInstance;
    }
    
    public void setBatchJobInstance(BatchJobInstance batchJobInstance) {
        this.batchJobInstance = batchJobInstance;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_TIME", length=19)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_TIME", length=19)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="STATUS", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="EXIT_CODE", length=100)
    public String getExitCode() {
        return this.exitCode;
    }
    
    public void setExitCode(String exitCode) {
        this.exitCode = exitCode;
    }

    
    @Column(name="EXIT_MESSAGE", length=2500)
    public String getExitMessage() {
        return this.exitMessage;
    }
    
    public void setExitMessage(String exitMessage) {
        this.exitMessage = exitMessage;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


