package com.inkubator.hrm.entity;
// Generated Sep 3, 2014 7:05:37 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * BenefitGroupRate generated by hbm2java
 */
@Entity
@Table(name="benefit_group_rate"
    ,catalog="hrm"
)
public class BenefitGroupRate  implements java.io.Serializable {


     private long id;
     private Integer version;
     private BenefitGroup benefitGroup;
     private GolonganJabatan golonganJabatan;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private Double nominal;

    public BenefitGroupRate() {
    }

	
    public BenefitGroupRate(long id) {
        this.id = id;
    }
    public BenefitGroupRate(long id, BenefitGroup benefitGroup, GolonganJabatan golonganJabatan, String createdBy, Date createdOn, String updatedBy, Date updatedOn, Double nominal) {
       this.id = id;
       this.benefitGroup = benefitGroup;
       this.golonganJabatan = golonganJabatan;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.nominal = nominal;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="benefit_group_id")
    public BenefitGroup getBenefitGroup() {
        return this.benefitGroup;
    }
    
    public void setBenefitGroup(BenefitGroup benefitGroup) {
        this.benefitGroup = benefitGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="golongan_jabatan_id")
    public GolonganJabatan getGolonganJabatan() {
        return this.golonganJabatan;
    }
    
    public void setGolonganJabatan(GolonganJabatan golonganJabatan) {
        this.golonganJabatan = golonganJabatan;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="nominal", precision=22, scale=0)
    public Double getNominal() {
        return this.nominal;
    }
    
    public void setNominal(Double nominal) {
        this.nominal = nominal;
    }




}


