package com.inkubator.hrm.entity;
// Generated Aug 7, 2014 10:29:27 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * BioEmergencyContact generated by hbm2java
 */
@Entity
@Table(name = "bio_emergency_contact", catalog = "hrm"
)
public class BioEmergencyContact implements java.io.Serializable {

    private long id;
    private Integer version;
    private BioData bioData;
    private City city;
    private FamilyRelation familyRelation;
    private String contactName;
    private String phoneNumber;
    private Boolean isSameHouse;
    private String address;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;

    public BioEmergencyContact() {
    }

    public BioEmergencyContact(long id) {
        this.id = id;
    }

    public BioEmergencyContact(long id, BioData bioData, City city, FamilyRelation familyRelation, String contactName, String phoneNumber, Boolean isSameHouse, String address, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
        this.id = id;
        this.bioData = bioData;
        this.city = city;
        this.familyRelation = familyRelation;
        this.contactName = contactName;
        this.phoneNumber = phoneNumber;
        this.isSameHouse = isSameHouse;
        this.address = address;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bio_data_id")
    public BioData getBioData() {
        return this.bioData;
    }

    public void setBioData(BioData bioData) {
        this.bioData = bioData;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "city_id")
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "keluarga_relasi_id")
    public FamilyRelation getFamilyRelation() {
        return this.familyRelation;
    }

    public void setFamilyRelation(FamilyRelation familyRelation) {
        this.familyRelation = familyRelation;
    }

    @Column(name = "contact_name", length = 100)
    public String getContactName() {
        return this.contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    @Column(name = "phone_number", length = 45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "is_same_house")
    public Boolean getIsSameHouse() {
        return this.isSameHouse;
    }

    public void setIsSameHouse(Boolean isSameHouse) {
        this.isSameHouse = isSameHouse;
    }

    @Column(name = "address", length = 100)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

}
