package com.inkubator.hrm.entity;
// Generated Aug 11, 2014 1:27:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * BioEmploymentHistory generated by hbm2java
 */
@Entity
@Table(name="bio_employment_history"
    ,catalog="hrm_payroll_backup"
)
public class BioEmploymentHistory  implements java.io.Serializable {


     private long id;
     private Integer version;
     private BioData bioData;
     private City city;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private Integer yearIn;
     private Integer yearOut;
     private String companyName;
     private String lastOccupation;
     private Double salary;
     private String jobSector;

    public BioEmploymentHistory() {
    }

    public BioEmploymentHistory(long id) {
        this.id = id;
    }
	
    public BioEmploymentHistory(long id, BioData bioData, City city) {
        this.id = id;
        this.bioData = bioData;
        this.city = city;
    }
    public BioEmploymentHistory(long id, BioData bioData, City city, String createdBy, Date createdOn, String updatedBy, Date updatedOn, Integer yearIn, Integer yearOut, String companyName, String lastOccupation, Double salary, String jobSector) {
       this.id = id;
       this.bioData = bioData;
       this.city = city;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.yearIn = yearIn;
       this.yearOut = yearOut;
       this.companyName = companyName;
       this.lastOccupation = lastOccupation;
       this.salary = salary;
       this.jobSector = jobSector;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bio_data_id", nullable=false)
    public BioData getBioData() {
        return this.bioData;
    }
    
    public void setBioData(BioData bioData) {
        this.bioData = bioData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="year_in")
    public Integer getYearIn() {
        return this.yearIn;
    }
    
    public void setYearIn(Integer yearIn) {
        this.yearIn = yearIn;
    }

    
    @Column(name="year_out")
    public Integer getYearOut() {
        return this.yearOut;
    }
    
    public void setYearOut(Integer yearOut) {
        this.yearOut = yearOut;
    }

    
    @Column(name="company_name", length=60)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="last_occupation", length=60)
    public String getLastOccupation() {
        return this.lastOccupation;
    }
    
    public void setLastOccupation(String lastOccupation) {
        this.lastOccupation = lastOccupation;
    }

    
    @Column(name="salary", precision=22, scale=0)
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    
    @Column(name="job_sector", length=60)
    public String getJobSector() {
        return this.jobSector;
    }
    
    public void setJobSector(String jobSector) {
        this.jobSector = jobSector;
    }




}


