package com.inkubator.hrm.entity;
// Generated Aug 11, 2014 1:21:52 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * BioInsurance generated by hbm2java
 */
@Entity
@Table(name="bio_insurance"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="no_policy") 
)
public class BioInsurance  implements java.io.Serializable {


     private long id;
     private Integer version;
     private BioData bioData;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private String noPolicy;
     private String instance;
     private String facility;
     private String description;

    public BioInsurance() {
    }

	
    public BioInsurance(long id, BioData bioData) {
        this.id = id;
        this.bioData = bioData;
    }
    public BioInsurance(long id, BioData bioData, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String noPolicy, String instance, String facility, String description) {
       this.id = id;
       this.bioData = bioData;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.noPolicy = noPolicy;
       this.instance = instance;
       this.facility = facility;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bio_data_id", nullable=false)
    public BioData getBioData() {
        return this.bioData;
    }
    
    public void setBioData(BioData bioData) {
        this.bioData = bioData;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="no_policy", unique=true, length=60)
    public String getNoPolicy() {
        return this.noPolicy;
    }
    
    public void setNoPolicy(String noPolicy) {
        this.noPolicy = noPolicy;
    }

    
    @Column(name="instance", length=60)
    public String getInstance() {
        return this.instance;
    }
    
    public void setInstance(String instance) {
        this.instance = instance;
    }

    
    @Column(name="facility", length=60)
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }

    
    @Column(name="description", length=65535, columnDefinition="Text")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


