package com.inkubator.hrm.entity;
// Generated Nov 3, 2014 2:13:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompanyPolicyJabatanId generated by hbm2java
 */
@Embeddable
public class CompanyPolicyJabatanId  implements java.io.Serializable {


     private long companyPolicyId;
     private long golJabId;

    public CompanyPolicyJabatanId() {
    }

    public CompanyPolicyJabatanId(long companyPolicyId, long golJabId) {
       this.companyPolicyId = companyPolicyId;
       this.golJabId = golJabId;
    }
   


    @Column(name="company_policy_id", nullable=false)
    public long getCompanyPolicyId() {
        return this.companyPolicyId;
    }
    
    public void setCompanyPolicyId(long companyPolicyId) {
        this.companyPolicyId = companyPolicyId;
    }


    @Column(name="gol_jab_id", nullable=false)
    public long getGolJabId() {
        return this.golJabId;
    }
    
    public void setGolJabId(long golJabId) {
        this.golJabId = golJabId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompanyPolicyJabatanId) ) return false;
		 CompanyPolicyJabatanId castOther = ( CompanyPolicyJabatanId ) other; 
         
		 return (this.getCompanyPolicyId()==castOther.getCompanyPolicyId())
 && (this.getGolJabId()==castOther.getGolJabId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCompanyPolicyId();
         result = 37 * result + (int) this.getGolJabId();
         return result;
   }   


}


