package com.inkubator.hrm.entity;
// Generated Jun 17, 2014 4:36:40 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * CostCenter generated by hbm2java
 */
@Entity
@Table(name = "coa", catalog="hrm_payroll_backup", uniqueConstraints =
        @UniqueConstraint(columnNames = "code"))
public class CostCenter implements java.io.Serializable {

    private long id;
    private Integer version;
    private CostCenter costCenter;
    private String code;
    private String name;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;
    private String description;
    private BigDecimal balance;
    private Set<Jabatan> jabatans = new HashSet<>(0);
    private Set<CostCenter> costCenters = new HashSet<>(0);
    private Set<PaySalaryJurnal> paySalaryJurnals = new HashSet<PaySalaryJurnal>(0);
    private Set<TravelComponentCostRate> travelComponentCostRates = new HashSet<TravelComponentCostRate>(0);
    private Set<BusinessTravelComponent> businessTravelComponents = new HashSet<BusinessTravelComponent>(0);
    private Set<ReimbursmentSchema> reimbursmentSchemas = new HashSet<ReimbursmentSchema>(0);

    public CostCenter() {
    }

    public CostCenter(long id) {
        this.id = id;
    }

    public CostCenter(long id, CostCenter costCenter, String code, String name, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String description, BigDecimal balance, Set<Jabatan> jabatans, Set<CostCenter> costCenters, Set<PaySalaryJurnal> paySalaryJurnals, Set<TravelComponentCostRate> travelComponentCostRates, Set<BusinessTravelComponent> businessTravelComponents, Set<ReimbursmentSchema> reimbursmentSchemas) {
        this.id = id;
        this.costCenter = costCenter;
        this.code = code;
        this.name = name;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
        this.description = description;
        this.balance = balance;
        this.jabatans = jabatans;
        this.costCenters = costCenters;
        this.paySalaryJurnals = paySalaryJurnals;
        this.travelComponentCostRates = travelComponentCostRates;
        this.businessTravelComponents = businessTravelComponents;
        this.reimbursmentSchemas = reimbursmentSchemas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    public CostCenter getCostCenter() {
        return this.costCenter;
    }

    public void setCostCenter(CostCenter costCenter) {
        this.costCenter = costCenter;
    }

    @Column(name = "code", unique = true, length = 6)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Column(name = "description", length = 65535, columnDefinition="Text")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "balance", precision = 10, scale = 0)
    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "costCenter")
    public Set<Jabatan> getJabatans() {
        return this.jabatans;
    }

    public void setJabatans(Set<Jabatan> jabatans) {
        this.jabatans = jabatans;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "costCenter")
    public Set<CostCenter> getCostCenters() {
        return this.costCenters;
    }

    public void setCostCenters(Set<CostCenter> costCenters) {
        this.costCenters = costCenters;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "costCenter")
    public Set<PaySalaryJurnal> getPaySalaryJurnals() {
        return paySalaryJurnals;
    }

    public void setPaySalaryJurnals(Set<PaySalaryJurnal> paySalaryJurnals) {
        this.paySalaryJurnals = paySalaryJurnals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "costCenter")
    public Set<TravelComponentCostRate> getTravelComponentCostRates() {
        return travelComponentCostRates;
    }

    public void setTravelComponentCostRates(Set<TravelComponentCostRate> travelComponentCostRates) {
        this.travelComponentCostRates = travelComponentCostRates;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "costCenter")
    public Set<BusinessTravelComponent> getBusinessTravelComponents() {
        return businessTravelComponents;
    }

    public void setBusinessTravelComponents(Set<BusinessTravelComponent> businessTravelComponents) {
        this.businessTravelComponents = businessTravelComponents;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "costCenter")
    public Set<ReimbursmentSchema> getReimbursmentSchemas() {
        return reimbursmentSchemas;
    }

    public void setReimbursmentSchemas(Set<ReimbursmentSchema> reimbursmentSchemas) {
        this.reimbursmentSchemas = reimbursmentSchemas;
    }
}
