package com.inkubator.hrm.entity;
// Generated Apr 9, 2015 1:19:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DepartementUnitLocationId generated by hbm2java
 */
@Embeddable
public class DepartementUnitLocationId  implements java.io.Serializable {


     private long departemenId;
     private long unitId;

    public DepartementUnitLocationId() {
    }

    public DepartementUnitLocationId(long departemenId, long unitId) {
       this.departemenId = departemenId;
       this.unitId = unitId;
    }
   


    @Column(name="departemen_id", nullable=false)
    public long getDepartemenId() {
        return this.departemenId;
    }
    
    public void setDepartemenId(long departemenId) {
        this.departemenId = departemenId;
    }


    @Column(name="unit_id", nullable=false)
    public long getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(long unitId) {
        this.unitId = unitId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DepartementUnitLocationId) ) return false;
		 DepartementUnitLocationId castOther = ( DepartementUnitLocationId ) other; 
         
		 return (this.getDepartemenId()==castOther.getDepartemenId())
 && (this.getUnitId()==castOther.getUnitId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getDepartemenId();
         result = 37 * result + (int) this.getUnitId();
         return result;
   }   


}


