package com.inkubator.hrm.entity;
// Generated Oct 20, 2014 2:41:54 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DepartementUploadCapture generated by hbm2java
 */
@Entity
@Table(name = "departement_upload_capture", catalog = "hrm_personalia"
)
public class DepartementUploadCapture implements java.io.Serializable {

    private DepartementUploadCaptureId id;
    private Department department;
    private MecineFinger mecineFinger;
    private String description;

    public DepartementUploadCapture() {
    }

    public DepartementUploadCapture(DepartementUploadCaptureId id, Department department, MecineFinger mecineFinger) {
        this.id = id;
        this.department = department;
        this.mecineFinger = mecineFinger;
    }

    public DepartementUploadCapture(DepartementUploadCaptureId id, Department department, MecineFinger mecineFinger, String description) {
        this.id = id;
        this.department = department;
        this.mecineFinger = mecineFinger;
        this.description = description;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "mesinId", column = @Column(name = "mesin_id", nullable = false)),
        @AttributeOverride(name = "departementId", column = @Column(name = "departement_id", nullable = false))})
    public DepartementUploadCaptureId getId() {
        return this.id;
    }

    public void setId(DepartementUploadCaptureId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "departement_id", nullable = false, insertable = false, updatable = false)
    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mesin_id", nullable = false, insertable = false, updatable = false)
    public MecineFinger getMecineFinger() {
        return this.mecineFinger;
    }

    public void setMecineFinger(MecineFinger mecineFinger) {
        this.mecineFinger = mecineFinger;
    }

    @Column(name = "description", length = 65535, columnDefinition = "Text")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
