package com.inkubator.hrm.entity;
// Generated Aug 25, 2014 1:32:27 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * EmpRotasi generated by hbm2java
 */
@Entity
@Table(name="_emp_rotasi"
    ,catalog="hrm"
)
public class EmpRotasi  implements java.io.Serializable {


     private long id;
     private Integer version;
     private EmpData empData;
     private Jabatan jabatanByNewFunctionId;
     private Jabatan jabatanByOldFunctionId;
     private String letterNumber;
     private Long oldBasicSalary;
     private Long newBasicSalary;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public EmpRotasi() {
    }

	
    public EmpRotasi(long id) {
        this.id = id;
    }
    public EmpRotasi(long id, EmpData empData, Jabatan jabatanByNewFunctionId, Jabatan jabatanByOldFunctionId, String letterNumber, Long oldBasicSalary, Long newBasicSalary, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.id = id;
       this.empData = empData;
       this.jabatanByNewFunctionId = jabatanByNewFunctionId;
       this.jabatanByOldFunctionId = jabatanByOldFunctionId;
       this.letterNumber = letterNumber;
       this.oldBasicSalary = oldBasicSalary;
       this.newBasicSalary = newBasicSalary;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_data_id")
    public EmpData getEmpData() {
        return this.empData;
    }
    
    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="new_function_id")
    public Jabatan getJabatanByNewFunctionId() {
        return this.jabatanByNewFunctionId;
    }
    
    public void setJabatanByNewFunctionId(Jabatan jabatanByNewFunctionId) {
        this.jabatanByNewFunctionId = jabatanByNewFunctionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="old_function_id")
    public Jabatan getJabatanByOldFunctionId() {
        return this.jabatanByOldFunctionId;
    }
    
    public void setJabatanByOldFunctionId(Jabatan jabatanByOldFunctionId) {
        this.jabatanByOldFunctionId = jabatanByOldFunctionId;
    }

    
    @Column(name="letter_number", length=45)
    public String getLetterNumber() {
        return this.letterNumber;
    }
    
    public void setLetterNumber(String letterNumber) {
        this.letterNumber = letterNumber;
    }

    
    @Column(name="old_basic_salary", precision=10, scale=0)
    public Long getOldBasicSalary() {
        return this.oldBasicSalary;
    }
    
    public void setOldBasicSalary(Long oldBasicSalary) {
        this.oldBasicSalary = oldBasicSalary;
    }

    
    @Column(name="new_basic_salary", precision=10, scale=0)
    public Long getNewBasicSalary() {
        return this.newBasicSalary;
    }
    
    public void setNewBasicSalary(Long newBasicSalary) {
        this.newBasicSalary = newBasicSalary;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


