package com.inkubator.hrm.entity;
// Generated May 20, 2014 10:25:51 AM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * FamilyRelation generated by hbm2java
 */
@Entity
@Table(name = "family_relation", catalog = "hrm"
)
public class FamilyRelation implements java.io.Serializable {

    private long id;
    private Integer version;
    private String relasiName;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;
    private Set<BioEmergencyContact> bioEmergencyContacts = new HashSet<BioEmergencyContact>(0);
    private Set<BioFamilyRelationship> bioFamilyRelationships = new HashSet<BioFamilyRelationship>(0);
    private String code;
    private String description;
    private Boolean isActive;
    private Boolean isDependent;

    public FamilyRelation() {
    }

    public FamilyRelation(long id) {
        this.id = id;
    }

    public FamilyRelation(long id, String relasiName, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String code, String description, Boolean isActive, Boolean isDependent) {
        this.id = id;
        this.relasiName = relasiName;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
        this.code = code;
        this.description = description;
        this.isActive = isActive;
        this.isDependent = isDependent;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "relasi_name", length = 60)
    public String getRelasiName() {
        return this.relasiName;
    }

    public void setRelasiName(String relasiName) {
        this.relasiName = relasiName;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "familyRelation")
    public Set<BioEmergencyContact> getBioEmergencyContacts() {
        return this.bioEmergencyContacts;
    }

    public void setBioEmergencyContacts(Set<BioEmergencyContact> bioEmergencyContacts) {
        this.bioEmergencyContacts = bioEmergencyContacts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "familyRelation")
    public Set<BioFamilyRelationship> getBioFamilyRelationships() {
        return bioFamilyRelationships;
    }

    public void setBioFamilyRelationships(Set<BioFamilyRelationship> bioFamilyRelationships) {
        this.bioFamilyRelationships = bioFamilyRelationships;
    }

    @Column(name = "code", unique = true, nullable = false)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "description", length = 225)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "status_active")
    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Column(name = "is_dependent")
    public Boolean getIsDependent(){
        return isDependent;
    }
    
    public void setIsDependent(Boolean isDependent){
        this.isDependent = isDependent;
    }
}
