package com.inkubator.hrm.entity;
// Generated Jul 14, 2014 2:09:36 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FavoriteMenu generated by hbm2java
 */
@Entity
@Table(name="favorite_menu"
    ,catalog="hrm_personalia"
)
public class FavoriteMenu  implements java.io.Serializable {


     private FavoriteMenuId id;
     private HrmUser hrmUser;
     private HrmMenu hrmMenu;
     private String deskripsi;

    public FavoriteMenu() {
    }

	
    public FavoriteMenu(FavoriteMenuId id, HrmUser hrmUser, HrmMenu hrmMenu) {
        this.id = id;
        this.hrmUser = hrmUser;
        this.hrmMenu = hrmMenu;
    }
    public FavoriteMenu(FavoriteMenuId id, HrmUser hrmUser, HrmMenu hrmMenu, String deskripsi) {
       this.id = id;
       this.hrmUser = hrmUser;
       this.hrmMenu = hrmMenu;
       this.deskripsi = deskripsi;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="menuId", column=@Column(name="menu_id", nullable=false) ) } )
    public FavoriteMenuId getId() {
        return this.id;
    }
    
    public void setId(FavoriteMenuId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public HrmUser getHrmUser() {
        return this.hrmUser;
    }
    
    public void setHrmUser(HrmUser hrmUser) {
        this.hrmUser = hrmUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_id", nullable=false, insertable=false, updatable=false)
    public HrmMenu getHrmMenu() {
        return this.hrmMenu;
    }
    
    public void setHrmMenu(HrmMenu hrmMenu) {
        this.hrmMenu = hrmMenu;
    }

    
    @Column(name="deskripsi", length=45)
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }




}


