package com.inkubator.hrm.entity;
// Generated May 9, 2014 9:50:44 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HrmUserRole generated by hbm2java
 */
@Entity
@Table(name="hrm_user_role"
    ,catalog="hrm_personalia"
)
public class HrmUserRole  implements java.io.Serializable {


     private HrmUserRoleId id;
     private HrmUser hrmUser;
     private HrmRole hrmRole;
     private String description;

    public HrmUserRole() {
    }

	
    public HrmUserRole(HrmUserRoleId id, HrmUser hrmUser, HrmRole hrmRole) {
        this.id = id;
        this.hrmUser = hrmUser;
        this.hrmRole = hrmRole;
    }
    public HrmUserRole(HrmUserRoleId id, HrmUser hrmUser, HrmRole hrmRole, String description) {
       this.id = id;
       this.hrmUser = hrmUser;
       this.hrmRole = hrmRole;
       this.description = description;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="roleId", column=@Column(name="role_id", nullable=false) ) } )
    public HrmUserRoleId getId() {
        return this.id;
    }
    
    public void setId(HrmUserRoleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public HrmUser getHrmUser() {
        return this.hrmUser;
    }
    
    public void setHrmUser(HrmUser hrmUser) {
        this.hrmUser = hrmUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false, insertable=false, updatable=false)
    public HrmRole getHrmRole() {
        return this.hrmRole;
    }
    
    public void setHrmRole(HrmRole hrmRole) {
        this.hrmRole = hrmRole;
    }

    
    @Column(name="description", length=65535, columnDefinition="Text")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


