package com.inkubator.hrm.entity;
// Generated Oct 14, 2014 10:35:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JabatanFakultyId generated by hbm2java
 */
@Embeddable
public class JabatanFakultyId  implements java.io.Serializable {


     private long jabatanId;
     private long fakultyId;

    public JabatanFakultyId() {
    }

    public JabatanFakultyId(long jabatanId, long fakultyId) {
       this.jabatanId = jabatanId;
       this.fakultyId = fakultyId;
    }
   


    @Column(name="jabatan_id", nullable=false)
    public long getJabatanId() {
        return this.jabatanId;
    }
    
    public void setJabatanId(long jabatanId) {
        this.jabatanId = jabatanId;
    }


    @Column(name="fakulty_id", nullable=false)
    public long getFakultyId() {
        return this.fakultyId;
    }
    
    public void setFakultyId(long fakultyId) {
        this.fakultyId = fakultyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JabatanFakultyId) ) return false;
		 JabatanFakultyId castOther = ( JabatanFakultyId ) other; 
         
		 return (this.getJabatanId()==castOther.getJabatanId())
 && (this.getFakultyId()==castOther.getFakultyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getJabatanId();
         result = 37 * result + (int) this.getFakultyId();
         return result;
   }   


}


