package com.inkubator.hrm.entity;
// Generated Jun 17, 2014 4:36:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * JabatanSpesifikasi generated by hbm2java
 */
@Entity
@Table(name="jabatan_spesifikasi"
    ,catalog="hrm"
)
public class JabatanSpesifikasi  implements java.io.Serializable {


     private long id;
     private Integer version;
     private SpecificationAbility specificationAbility;
     private Jabatan jabatan;
     private String value;
     private String optionAbility;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public JabatanSpesifikasi() {
    }

	
    public JabatanSpesifikasi(long id) {
        this.id = id;
    }
    public JabatanSpesifikasi(long id, SpecificationAbility specificationAbility, Jabatan jabatan, String value, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String optionAbility) {
       this.id = id;
       this.specificationAbility = specificationAbility;
       this.jabatan = jabatan;
       this.value = value;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.optionAbility = optionAbility;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="specification_id")
    public SpecificationAbility getSpecificationAbility() {
        return this.specificationAbility;
    }
    
    public void setSpecificationAbility(SpecificationAbility specificationAbility) {
        this.specificationAbility = specificationAbility;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jabatan_id")
    public Jabatan getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(Jabatan jabatan) {
        this.jabatan = jabatan;
    }

    
    @Column(name="value", length=45)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "option_ability", nullable = false)
    public String getOptionAbility() {
        return optionAbility;
    }

    public void setOptionAbility(String optionAbility) {
        this.optionAbility = optionAbility;
    }
    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


