package com.inkubator.hrm.entity;
// Generated Jun 17, 2014 4:36:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Jabatan generated by hbm2java
 */
@Entity
@Table(name="jabatan"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class Jabatan  implements java.io.Serializable {


     private long id;
     private Integer version;
     private CostCenter costCenter;
     private GolonganJabatan golonganJabatan;
     private Department department;
     private UnitKerja unitKerja;
     private String code;
     private String name;
     private String tujuanJabatan;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private Set<JabatanDeskripsi> jabatanDeskripsis = new HashSet<JabatanDeskripsi>(0);
     private Set<JabatanSpesifikasi> jabatanSpesifikasis = new HashSet<JabatanSpesifikasi>(0);

    public Jabatan() {
    }

	
    public Jabatan(long id) {
        this.id = id;
    }
    public Jabatan(long id, CostCenter costCenter, GolonganJabatan golonganJabatan, Department department, UnitKerja unitKerja, String code, String name, String tujuanJabatan, String createdBy, Date createdOn, String updatedBy, Date updatedOn, Set<JabatanDeskripsi> jabatanDeskripsis, Set<JabatanSpesifikasi> jabatanSpesifikasis) {
       this.id = id;
       this.costCenter = costCenter;
       this.golonganJabatan = golonganJabatan;
       this.department = department;
       this.unitKerja = unitKerja;
       this.code = code;
       this.name = name;
       this.tujuanJabatan = tujuanJabatan;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.jabatanDeskripsis = jabatanDeskripsis;
       this.jabatanSpesifikasis = jabatanSpesifikasis;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cost_center_id")
    public CostCenter getCostCenter() {
        return this.costCenter;
    }
    
    public void setCostCenter(CostCenter costCenter) {
        this.costCenter = costCenter;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gol_jabatan_id")
    public GolonganJabatan getGolonganJabatan() {
        return this.golonganJabatan;
    }
    
    public void setGolonganJabatan(GolonganJabatan golonganJabatan) {
        this.golonganJabatan = golonganJabatan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="departement_id")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_kerja_id")
    public UnitKerja getUnitKerja() {
        return this.unitKerja;
    }
    
    public void setUnitKerja(UnitKerja unitKerja) {
        this.unitKerja = unitKerja;
    }

    
    @Column(name="code", unique=true, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="tujuan_jabatan", length=65535)
    public String getTujuanJabatan() {
        return this.tujuanJabatan;
    }
    
    public void setTujuanJabatan(String tujuanJabatan) {
        this.tujuanJabatan = tujuanJabatan;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jabatan")
    public Set<JabatanDeskripsi> getJabatanDeskripsis() {
        return this.jabatanDeskripsis;
    }
    
    public void setJabatanDeskripsis(Set<JabatanDeskripsi> jabatanDeskripsis) {
        this.jabatanDeskripsis = jabatanDeskripsis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jabatan")
    public Set<JabatanSpesifikasi> getJabatanSpesifikasis() {
        return this.jabatanSpesifikasis;
    }
    
    public void setJabatanSpesifikasis(Set<JabatanSpesifikasi> jabatanSpesifikasis) {
        this.jabatanSpesifikasis = jabatanSpesifikasis;
    }




}


