package com.inkubator.hrm.entity;
// Generated Oct 14, 2014 10:35:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JabatanMajorId generated by hbm2java
 */
@Embeddable
public class JabatanMajorId  implements java.io.Serializable {


     private long jabatanId;
     private long majorId;

    public JabatanMajorId() {
    }

    public JabatanMajorId(long jabatanId, long majorId) {
       this.jabatanId = jabatanId;
       this.majorId = majorId;
    }
   


    @Column(name="jabatan_id", nullable=false)
    public long getJabatanId() {
        return this.jabatanId;
    }
    
    public void setJabatanId(long jabatanId) {
        this.jabatanId = jabatanId;
    }


    @Column(name="major_id", nullable=false)
    public long getMajorId() {
        return this.majorId;
    }
    
    public void setMajorId(long majorId) {
        this.majorId = majorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JabatanMajorId) ) return false;
		 JabatanMajorId castOther = ( JabatanMajorId ) other; 
         
		 return (this.getJabatanId()==castOther.getJabatanId())
 && (this.getMajorId()==castOther.getMajorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getJabatanId();
         result = 37 * result + (int) this.getMajorId();
         return result;
   }   


}


