package com.inkubator.hrm.entity;
// Generated Oct 14, 2014 10:35:26 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JabatanEdukasi generated by hbm2java
 */
@Entity
@Table(name = "jabatan_edukasi", catalog="hrm_payroll_backup"
)
public class JabatanEdukasi implements java.io.Serializable {

    private JabatanEdukasiId id;
    private EducationLevel educationLevel;
    private Jabatan jabatan;
    private String descripstion;

    public JabatanEdukasi() {
    }

    public JabatanEdukasi(JabatanEdukasiId id, EducationLevel educationLevel, Jabatan jabatan) {
        this.id = id;
        this.educationLevel = educationLevel;
        this.jabatan = jabatan;
    }

    public JabatanEdukasi(JabatanEdukasiId id, EducationLevel educationLevel, Jabatan jabatan, String descripstion) {
        this.id = id;
        this.educationLevel = educationLevel;
        this.jabatan = jabatan;
        this.descripstion = descripstion;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "jabatanId", column = @Column(name = "jabatan_id", nullable = false)),
        @AttributeOverride(name = "eductionId", column = @Column(name = "eduction_id", nullable = false))})
    public JabatanEdukasiId getId() {
        return this.id;
    }

    public void setId(JabatanEdukasiId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "eduction_id", nullable = false, insertable = false, updatable = false)
    public EducationLevel getEducationLevel() {
        return this.educationLevel;
    }

    public void setEducationLevel(EducationLevel educationLevel) {
        this.educationLevel = educationLevel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "jabatan_id", nullable = false, insertable = false, updatable = false)
    public Jabatan getJabatan() {
        return this.jabatan;
    }

    public void setJabatan(Jabatan jabatan) {
        this.jabatan = jabatan;
    }

    @Column(name = "description", length = 65535, columnDefinition = "Text")
    public String getDescripstion() {
        return this.descripstion;
    }

    public void setDescripstion(String descripstion) {
        this.descripstion = descripstion;
    }
}
