package com.inkubator.hrm.entity;
// Generated Jul 7, 2014 11:47:53 AM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * KlasifikasiKerja generated by hbm2java
 */
@Entity
@Table(name="klasifikasi_kerja"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class KlasifikasiKerja  implements java.io.Serializable {


     private long id;
     private Integer version;
     private GolonganJabatan golonganJabatanByStrataAtasGoljabId;
     private GolonganJabatan golonganJabatanByStrataBawahGoljabId;
     private String createdBy;
     private Date createdOn;
     private String code;
     private String name;
     private String updatedBy;
     private Date updatedOn;
     private String description;
     private String klasifikasiKerjaCode;
     private String klasifikasiKerjaName;
     private Set<OrgKlasifikasiJobFamily> orgKlasifikasiJobFamilies = new HashSet<OrgKlasifikasiJobFamily>(0);
     private List<GolonganJabatan> listGolJab = new ArrayList<GolonganJabatan>();

    public KlasifikasiKerja() {
    }

	
    public KlasifikasiKerja(long id) {
        this.id = id;
    }
    public KlasifikasiKerja(long id, GolonganJabatan golonganJabatanByStrataAtasGoljabId, GolonganJabatan golonganJabatanByStrataBawahGoljabId, String createdBy, Date createdOn, String code, String name, String updatedBy, Date updatedOn, String description, String klasifikasiKerjaCode, String klasifikasiKerjaName, Set<OrgKlasifikasiJobFamily> orgKlasifikasiJobFamilies) {
       this.id = id;
       this.golonganJabatanByStrataAtasGoljabId = golonganJabatanByStrataAtasGoljabId;
       this.golonganJabatanByStrataBawahGoljabId = golonganJabatanByStrataBawahGoljabId;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.code = code;
       this.name = name;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.description = description;
       this.klasifikasiKerjaCode = klasifikasiKerjaCode;
       this.klasifikasiKerjaName = klasifikasiKerjaName;
       this.orgKlasifikasiJobFamilies = orgKlasifikasiJobFamilies;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="strata_atas_goljab_id")
    public GolonganJabatan getGolonganJabatanByStrataAtasGoljabId() {
        return this.golonganJabatanByStrataAtasGoljabId;
    }
    
    public void setGolonganJabatanByStrataAtasGoljabId(GolonganJabatan golonganJabatanByStrataAtasGoljabId) {
        this.golonganJabatanByStrataAtasGoljabId = golonganJabatanByStrataAtasGoljabId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="strata_bawah_goljab_id")
    public GolonganJabatan getGolonganJabatanByStrataBawahGoljabId() {
        return this.golonganJabatanByStrataBawahGoljabId;
    }
    
    public void setGolonganJabatanByStrataBawahGoljabId(GolonganJabatan golonganJabatanByStrataBawahGoljabId) {
        this.golonganJabatanByStrataBawahGoljabId = golonganJabatanByStrataBawahGoljabId;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="code", unique=true, length=8)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="klasifikasi_kerja_code", length=8)
    public String getKlasifikasiKerjaCode() {
        return this.klasifikasiKerjaCode;
    }
    
    public void setKlasifikasiKerjaCode(String klasifikasiKerjaCode) {
        this.klasifikasiKerjaCode = klasifikasiKerjaCode;
    }

    
    @Column(name="klasifikasi_kerja_name", length=60)
    public String getKlasifikasiKerjaName() {
        return this.klasifikasiKerjaName;
    }
    
    public void setKlasifikasiKerjaName(String klasifikasiKerjaName) {
        this.klasifikasiKerjaName = klasifikasiKerjaName;
    }

@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "klasifikasiKerja", orphanRemoval = true)
    public Set<OrgKlasifikasiJobFamily> getOrgKlasifikasiJobFamilies() {
        return this.orgKlasifikasiJobFamilies;
    }
    
    public void setOrgKlasifikasiJobFamilies(Set<OrgKlasifikasiJobFamily> orgKlasifikasiJobFamilies) {
        this.orgKlasifikasiJobFamilies = orgKlasifikasiJobFamilies;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + (int) (this.id ^ (this.id >>> 32));
        hash = 31 * hash + Objects.hashCode(this.version);
        hash = 31 * hash + Objects.hashCode(this.createdBy);
        hash = 31 * hash + Objects.hashCode(this.createdOn);
        hash = 31 * hash + Objects.hashCode(this.code);
        hash = 31 * hash + Objects.hashCode(this.name);
        hash = 31 * hash + Objects.hashCode(this.updatedBy);
        hash = 31 * hash + Objects.hashCode(this.updatedOn);
        hash = 31 * hash + Objects.hashCode(this.description);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final KlasifikasiKerja other = (KlasifikasiKerja) obj;
        if (this.id != other.id) {
            return false;
        }
        if (!Objects.equals(this.version, other.version)) {
            return false;
        }
        if (!Objects.equals(this.createdBy, other.createdBy)) {
            return false;
        }
        if (!Objects.equals(this.createdOn, other.createdOn)) {
            return false;
        }
        if (!Objects.equals(this.code, other.code)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.updatedBy, other.updatedBy)) {
            return false;
        }
        if (!Objects.equals(this.updatedOn, other.updatedOn)) {
            return false;
        }
        if (!Objects.equals(this.description, other.description)) {
            return false;
        }
        return true;
    }

    @Transient
    public List<GolonganJabatan> getListGolJab() {
        return listGolJab;
    }

    public void setListGolJab(List<GolonganJabatan> listGolJab) {
        this.listGolJab = listGolJab;
    }




}


