package com.inkubator.hrm.entity;
// Generated Jul 7, 2014 11:47:53 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KlasifikasiKerjaJabatan generated by hbm2java
 */
@Entity
@Table(name="klasifikasi_kerja_jabatan"
    ,catalog="hrm_payroll_backup"
)
public class KlasifikasiKerjaJabatan  implements java.io.Serializable {


     private KlasifikasiKerjaJabatanId id;
     private KlasifikasiKerja klasifikasiKerja;
     private Jabatan jabatan;
     private String description;

    public KlasifikasiKerjaJabatan() {
    }

	
    public KlasifikasiKerjaJabatan(KlasifikasiKerjaJabatanId id, KlasifikasiKerja klasifikasiKerja, Jabatan jabatan) {
        this.id = id;
        this.klasifikasiKerja = klasifikasiKerja;
        this.jabatan = jabatan;
    }
    public KlasifikasiKerjaJabatan(KlasifikasiKerjaJabatanId id, KlasifikasiKerja klasifikasiKerja, Jabatan jabatan, String description) {
       this.id = id;
       this.klasifikasiKerja = klasifikasiKerja;
       this.jabatan = jabatan;
       this.description = description;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="jabatanId", column=@Column(name="jabatan_id", nullable=false) ), 
        @AttributeOverride(name="klasifikasiKerjaId", column=@Column(name="klasifikasi_kerja_id", nullable=false) ) } )
    public KlasifikasiKerjaJabatanId getId() {
        return this.id;
    }
    
    public void setId(KlasifikasiKerjaJabatanId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="klasifikasi_kerja_id", nullable=false, insertable=false, updatable=false)
    public KlasifikasiKerja getKlasifikasiKerja() {
        return this.klasifikasiKerja;
    }
    
    public void setKlasifikasiKerja(KlasifikasiKerja klasifikasiKerja) {
        this.klasifikasiKerja = klasifikasiKerja;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jabatan_id", nullable=false, insertable=false, updatable=false)
    public Jabatan getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(Jabatan jabatan) {
        this.jabatan = jabatan;
    }

    
    @Column(name="description", length=65535, columnDefinition="Text")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


