package com.inkubator.hrm.entity;
// Generated Jun 17, 2015 2:17:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * KlasifikasiKerjaLevel generated by hbm2java
 */
@Entity
@Table(name="klasifikasi_kerja_level"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class KlasifikasiKerjaLevel  implements java.io.Serializable {


     private long id;
     private Integer version;
     private KlasifikasiKerja klasifikasiKerja;
     private String code;
     private String name;
     private String description;
     private Date createdOn;
     private String createdBy;
     private String updatedBy;
     private Date updatedOn;

    public KlasifikasiKerjaLevel() {
    }

	
    public KlasifikasiKerjaLevel(long id) {
        this.id = id;
    }
    public KlasifikasiKerjaLevel(long id, KlasifikasiKerja klasifikasiKerja, String code, String name, String description, Date createdOn, String createdBy, String updatedBy, Date updatedOn) {
       this.id = id;
       this.klasifikasiKerja = klasifikasiKerja;
       this.code = code;
       this.name = name;
       this.description = description;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="klasifikasi_kerja_id")
    public KlasifikasiKerja getKlasifikasiKerja() {
        return this.klasifikasiKerja;
    }
    
    public void setKlasifikasiKerja(KlasifikasiKerja klasifikasiKerja) {
        this.klasifikasiKerja = klasifikasiKerja;
    }

    
    @Column(name="code", unique=true, length=8)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


