package com.inkubator.hrm.entity;
// Generated Jul 7, 2014 11:47:53 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KlasifikasiKerjaJabatanId generated by hbm2java
 */
@Embeddable
public class KlasifikasiKerjaJabatanId  implements java.io.Serializable {


     private long jabatanId;
     private long klasifikasiKerjaId;

    public KlasifikasiKerjaJabatanId() {
    }

    public KlasifikasiKerjaJabatanId(long jabatanId, long klasifikasiKerjaId) {
       this.jabatanId = jabatanId;
       this.klasifikasiKerjaId = klasifikasiKerjaId;
    }
   


    @Column(name="jabatan_id", nullable=false)
    public long getJabatanId() {
        return this.jabatanId;
    }
    
    public void setJabatanId(long jabatanId) {
        this.jabatanId = jabatanId;
    }


    @Column(name="klasifikasi_kerja_id", nullable=false)
    public long getKlasifikasiKerjaId() {
        return this.klasifikasiKerjaId;
    }
    
    public void setKlasifikasiKerjaId(long klasifikasiKerjaId) {
        this.klasifikasiKerjaId = klasifikasiKerjaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KlasifikasiKerjaJabatanId) ) return false;
		 KlasifikasiKerjaJabatanId castOther = ( KlasifikasiKerjaJabatanId ) other; 
         
		 return (this.getJabatanId()==castOther.getJabatanId())
 && (this.getKlasifikasiKerjaId()==castOther.getKlasifikasiKerjaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getJabatanId();
         result = 37 * result + (int) this.getKlasifikasiKerjaId();
         return result;
   }   


}


