package com.inkubator.hrm.entity;
// Generated Dec 14, 2015 1:25:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * LicenseApp generated by hbm2java
 */
@Entity
@Table(name="license_app"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class LicenseApp  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String name;
     private Date startDate;
     private Date endDate;
     private String licenseType;
     private String licenseValue;
     private String licenseStatus;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public LicenseApp() {
    }

	
    public LicenseApp(long id) {
        this.id = id;
    }
    public LicenseApp(long id, String name, Date startDate, Date endDate, String licenseType, String licenseValue, String licenseStatus, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.id = id;
       this.name = name;
       this.startDate = startDate;
       this.endDate = endDate;
       this.licenseType = licenseType;
       this.licenseValue = licenseValue;
       this.licenseStatus = licenseStatus;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="name", unique=true, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="license_type", length=45)
    public String getLicenseType() {
        return this.licenseType;
    }
    
    public void setLicenseType(String licenseType) {
        this.licenseType = licenseType;
    }

    
    @Column(name="license_value", length=65535)
    public String getLicenseValue() {
        return this.licenseValue;
    }
    
    public void setLicenseValue(String licenseValue) {
        this.licenseValue = licenseValue;
    }

    
    @Column(name="license_status", length=45)
    public String getLicenseStatus() {
        return this.licenseStatus;
    }
    
    public void setLicenseStatus(String licenseStatus) {
        this.licenseStatus = licenseStatus;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


