package com.inkubator.hrm.entity;
// Generated Mar 26, 2015 2:31:33 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LoanNewApplicationInstallment generated by hbm2java
 */
@Entity
@Table(name = "loan_new_application_installment", catalog = "hrm"
)
public class LoanNewApplicationInstallment implements java.io.Serializable {

    private long id;
    private Integer version;
    private LoanNewApplication loanNewApplication;
    private Integer numOfInstallment;
    private Date installmentDate;
    private Double interestNominal;
    private Double basicNominal;
    private Double totalPayment;
    private Double remainingBasic;
    private Date createdOn;
    private Date updatedOn;
    private String createdBy;
    private String updatedBy;

    public LoanNewApplicationInstallment() {
    }

    public LoanNewApplicationInstallment(long id, Integer numOfInstallment) {
        this.id = id;
        this.numOfInstallment = numOfInstallment;
    }

    public LoanNewApplicationInstallment(long id, LoanNewApplication loanNewApplication, Integer numOfInstallment, Date installmentDate, Double interestNominal, Double basicNominal, Date createdOn, Date updatedOn, String createdBy, String updatedBy) {
        this.id = id;
        this.loanNewApplication = loanNewApplication;
        this.numOfInstallment = numOfInstallment;
        this.installmentDate = installmentDate;
        this.interestNominal = interestNominal;
        this.basicNominal = basicNominal;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loan_new_application_id")
    public LoanNewApplication getLoanNewApplication() {
        return this.loanNewApplication;
    }

    public void setLoanNewApplication(LoanNewApplication loanNewApplication) {
        this.loanNewApplication = loanNewApplication;
    }

    @Column(name = "num_of_installment", nullable = false)
    public Integer getNumOfInstallment() {
        return this.numOfInstallment;
    }

    public void setNumOfInstallment(Integer numOfInstallment) {
        this.numOfInstallment = numOfInstallment;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "installment_date", length = 10)
    public Date getInstallmentDate() {
        return this.installmentDate;
    }

    public void setInstallmentDate(Date installmentDate) {
        this.installmentDate = installmentDate;
    }

    @Column(name = "interest_nominal", precision = 10, scale = 0, nullable = false)
    public Double getInterestNominal() {
        return this.interestNominal;
    }

    public void setInterestNominal(Double interestNominal) {
        this.interestNominal = interestNominal;
    }

    @Column(name = "basic_nominal", precision = 10, scale = 0, nullable = false)
    public Double getBasicNominal() {
        return this.basicNominal;
    }

    public void setBasicNominal(Double basicNominal) {
        this.basicNominal = basicNominal;
    }

    @Column(name = "total_payment", nullable = false)
    public Double getTotalPayment() {
        return totalPayment;
    }

    public void setTotalPayment(Double totalPayment) {
        this.totalPayment = totalPayment;
    }
    
    @Column(name="remaining_basic", nullable = false)
    public Double getRemainingBasic() {
        return remainingBasic;
    }

    public void setRemainingBasic(Double remainingBasic) {
        this.remainingBasic = remainingBasic;
    }

    

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

}
