package com.inkubator.hrm.entity;
// Generated Mar 26, 2015 1:07:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * LoanNewType generated by hbm2java
 */
@Entity
@Table(name = "loan_new_type", catalog = "hrm", uniqueConstraints = {
    @UniqueConstraint(columnNames = "loan_type_code"),
    @UniqueConstraint(columnNames = "loan_type_name")}
)
public class LoanNewType implements java.io.Serializable {

    private long id;
    private Integer version;
    private Currency currency;
    private String loanTypeName;
    private String loanTypeCode;
    private String description;
    private Integer roundingStatus;
    private Integer interestMethod;
    private BigDecimal interest;
    private Date createdOn;
    private String createdBy;
    private String updatedBy;
    private Date updatedOn;
    private Set<LoanNewApplication> loanNewApplications = new HashSet<LoanNewApplication>(0);
    private Set<LoanNewSchemaListOfType> loanNewSchemaListOfTypes = new HashSet<LoanNewSchemaListOfType>(0);

    public LoanNewType() {
    }

    public LoanNewType(long id) {
        this.id = id;
    }

    public LoanNewType(long id, Currency currency, String loanTypeName, String loanTypeCode, Integer roundingStatus, Integer interestMethod, long BigDecimal) {
        this.id = id;
        this.currency = currency;
        this.loanTypeName = loanTypeName;
        this.loanTypeCode = loanTypeCode;
        this.roundingStatus = roundingStatus;
        this.interestMethod = interestMethod;
        this.interest = interest;
    }

    public LoanNewType(long id, Currency currency, String loanTypeName, String loanTypeCode, String description, Integer roundingStatus, Integer interestMethod, BigDecimal interest, Date createdOn, String createdBy, String updatedBy, Date updatedOn, Set<LoanNewApplication> loanNewApplications, Set<LoanNewSchemaListOfType> loanNewSchemaListOfTypes) {
        this.id = id;
        this.currency = currency;
        this.loanTypeName = loanTypeName;
        this.loanTypeCode = loanTypeCode;
        this.description = description;
        this.roundingStatus = roundingStatus;
        this.interestMethod = interestMethod;
        this.interest = interest;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
        this.loanNewApplications = loanNewApplications;
        this.loanNewSchemaListOfTypes = loanNewSchemaListOfTypes;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "currency_id", nullable = false)
    public Currency getCurrency() {
        return this.currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    @Column(name = "loan_type_name", unique = true, nullable = false, length = 45)
    public String getLoanTypeName() {
        return this.loanTypeName;
    }

    public void setLoanTypeName(String loanTypeName) {
        this.loanTypeName = loanTypeName;
    }

    @Column(name = "loan_type_code", unique = true, nullable = false, length = 45)
    public String getLoanTypeCode() {
        return this.loanTypeCode;
    }

    public void setLoanTypeCode(String loanTypeCode) {
        this.loanTypeCode = loanTypeCode;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "rounding_status", nullable = false)
    public Integer getRoundingStatus() {
        return this.roundingStatus;
    }

    public void setRoundingStatus(Integer roundingStatus) {
        this.roundingStatus = roundingStatus;
    }

    @Column(name = "interest_method", nullable = false)
    public Integer getInterestMethod() {
        return this.interestMethod;
    }

    public void setInterestMethod(Integer interestMethod) {
        this.interestMethod = interestMethod;
    }

    @Column(name = "interest", nullable = false, precision = 10, scale = 0)
    public BigDecimal getInterest() {
        return this.interest;
    }

    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loanNewType")
    public Set<LoanNewApplication> getLoanNewApplications() {
        return this.loanNewApplications;
    }

    public void setLoanNewApplications(Set<LoanNewApplication> loanNewApplications) {
        this.loanNewApplications = loanNewApplications;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loanNewType")
    public Set<LoanNewSchemaListOfType> getLoanNewSchemaListOfTypes() {
        return this.loanNewSchemaListOfTypes;
    }

    public void setLoanNewSchemaListOfTypes(Set<LoanNewSchemaListOfType> loanNewSchemaListOfTypes) {
        this.loanNewSchemaListOfTypes = loanNewSchemaListOfTypes;
    }

}
