package com.inkubator.hrm.entity;
// Generated Apr 13, 2015 10:45:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * LoanNewCancelation generated by hbm2java
 */
@Entity
@Table(name="loan_new_cancelation"
    ,catalog="hrm"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cancelation_code"), @UniqueConstraint(columnNames="approval_activity_number")} 
)
public class LoanNewCancelation  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String cancelationCode;
     private long loanNewApplicationId;
     private String approvalActivityNumber;
     private Date cancelationDate;
     private String reason;
     private Date createdOn;
     private String createdBy;
     private String updatedBy;
     private Date updatedOn;

    public LoanNewCancelation() {
    }

	
    public LoanNewCancelation(long id, String cancelationCode, long loanNewApplicationId) {
        this.id = id;
        this.cancelationCode = cancelationCode;
        this.loanNewApplicationId = loanNewApplicationId;
    }
    public LoanNewCancelation(long id, String cancelationCode, long loanNewApplicationId, String approvalActivityNumber, Date cancelationDate, String reason, Date createdOn, String createdBy, String updatedBy, Date updatedOn) {
       this.id = id;
       this.cancelationCode = cancelationCode;
       this.loanNewApplicationId = loanNewApplicationId;
       this.approvalActivityNumber = approvalActivityNumber;
       this.cancelationDate = cancelationDate;
       this.reason = reason;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="cancelation_code", unique=true, nullable=false, length=10)
    public String getCancelationCode() {
        return this.cancelationCode;
    }
    
    public void setCancelationCode(String cancelationCode) {
        this.cancelationCode = cancelationCode;
    }

    
    @Column(name="loan_new_application_id", nullable=false)
    public long getLoanNewApplicationId() {
        return this.loanNewApplicationId;
    }
    
    public void setLoanNewApplicationId(long loanNewApplicationId) {
        this.loanNewApplicationId = loanNewApplicationId;
    }

    
    @Column(name="approval_activity_number", unique=true, length=45)
    public String getApprovalActivityNumber() {
        return this.approvalActivityNumber;
    }
    
    public void setApprovalActivityNumber(String approvalActivityNumber) {
        this.approvalActivityNumber = approvalActivityNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cancelation_date", length=10)
    public Date getCancelationDate() {
        return this.cancelationDate;
    }
    
    public void setCancelationDate(Date cancelationDate) {
        this.cancelationDate = cancelationDate;
    }

    
    @Column(name="reason")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


