package com.inkubator.hrm.entity;
// Generated Apr 16, 2015 9:06:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * LoanNewDibursement generated by hbm2java
 */
@Entity
@Table(name="loan_new_disbursement"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="dibursement_code") 
)
public class LoanNewDisbursement  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String dibursementCode;
     private Date dibursementDate;
     private Long coaId;
     private String description;
     private Date createdOn;
     private String createdBy;
     private Set<LoanNewDisbursementList> loanNewDibursementLists = new HashSet<LoanNewDisbursementList>(0);

    public LoanNewDisbursement() {
    }

	
    public LoanNewDisbursement(long id, String dibursementCode) {
        this.id = id;
        this.dibursementCode = dibursementCode;
    }
    public LoanNewDisbursement(long id, String dibursementCode, Date dibursementDate, Long coaId, String description, Date createdOn, String createdBy, Set<LoanNewDisbursementList> loanNewDibursementLists) {
       this.id = id;
       this.dibursementCode = dibursementCode;
       this.dibursementDate = dibursementDate;
       this.coaId = coaId;
       this.description = description;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.loanNewDibursementLists = loanNewDibursementLists;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="dibursement_code", unique=true, nullable=false, length=60)
    public String getDibursementCode() {
        return this.dibursementCode;
    }
    
    public void setDibursementCode(String dibursementCode) {
        this.dibursementCode = dibursementCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dibursement_date", length=10)
    public Date getDibursementDate() {
        return this.dibursementDate;
    }
    
    public void setDibursementDate(Date dibursementDate) {
        this.dibursementDate = dibursementDate;
    }

    
    @Column(name="coa_id")
    public Long getCoaId() {
        return this.coaId;
    }
    
    public void setCoaId(Long coaId) {
        this.coaId = coaId;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loanNewDisbursement")
    public Set<LoanNewDisbursementList> getLoanNewDibursementLists() {
        return this.loanNewDibursementLists;
    }
    
    public void setLoanNewDibursementLists(Set<LoanNewDisbursementList> loanNewDibursementLists) {
        this.loanNewDibursementLists = loanNewDibursementLists;
    }




}


