package com.inkubator.hrm.entity;
// Generated Apr 16, 2015 9:06:30 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoanNewDibursementList generated by hbm2java
 */
@Entity
@Table(name = "loan_new_disbursement_list", catalog = "hrm"
)
public class LoanNewDisbursementList implements java.io.Serializable {

    private long id;
    private LoanNewApplication loanNewApplication;
    private LoanNewDisbursement loanNewDisbursement;
    private Date createdOn;
    private String createdBy;

    public LoanNewDisbursementList() {
    }

    public LoanNewDisbursementList(long id, LoanNewApplication loanNewApplication, LoanNewDisbursement loanNewDibursement) {
        this.id = id;
        this.loanNewApplication = loanNewApplication;
        this.loanNewDisbursement = loanNewDibursement;
    }

    public LoanNewDisbursementList(long id, LoanNewApplication loanNewApplication, LoanNewDisbursement loanNewDibursement, Date createdOn, String createdBy) {
        this.id = id;
        this.loanNewApplication = loanNewApplication;
        this.loanNewDisbursement = loanNewDibursement;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loan_new_application_id", nullable = false)
    public LoanNewApplication getLoanNewApplication() {
        return this.loanNewApplication;
    }

    public void setLoanNewApplication(LoanNewApplication loanNewApplication) {
        this.loanNewApplication = loanNewApplication;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loan_new_dibursement_id", nullable = false)
    public LoanNewDisbursement getLoanNewDisbursement() {
        return this.loanNewDisbursement;
    }

    public void setLoanNewDisbursement(LoanNewDisbursement loanNewDibursement) {
        this.loanNewDisbursement = loanNewDibursement;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

}
