package com.inkubator.hrm.entity;
// Generated May 9, 2014 9:50:44 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginHistory generated by hbm2java
 */
@Entity
@Table(name = "login_history", catalog="hrm_payroll_backup"
)
public class LoginHistory implements java.io.Serializable {

    private long id;
    private HrmUser hrmUser;
    private Date loginDate;
    private Date logOutDate;
    private String ipAddress;
    private String languange;
    private String appName;

    public LoginHistory() {
    }

    public LoginHistory(long id) {
        this.id = id;
    }

    public LoginHistory(long id, HrmUser hrmUser, Date loginDate, Date logOutDate, String ipAddress, String languange) {
        this.id = id;
        this.hrmUser = hrmUser;
        this.loginDate = loginDate;
        this.logOutDate = logOutDate;
        this.ipAddress = ipAddress;
        this.languange = languange;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    public HrmUser getHrmUser() {
        return this.hrmUser;
    }

    public void setHrmUser(HrmUser hrmUser) {
        this.hrmUser = hrmUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LOGIN_DATE", length = 19)
    public Date getLoginDate() {
        return this.loginDate;
    }

    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LOG_OUT_DATE", length = 19)
    public Date getLogOutDate() {
        return this.logOutDate;
    }

    public void setLogOutDate(Date logOutDate) {
        this.logOutDate = logOutDate;
    }

    @Column(name = "IP_ADDRESS", length = 45)
    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Column(name = "LANGUANGE", length = 5)
    public String getLanguange() {
        return this.languange;
    }

    public void setLanguange(String languange) {
        this.languange = languange;
    }

    @Column(name = "app_name", length = 30)
    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

}
