package com.inkubator.hrm.entity;
// Generated Jun 3, 2015 4:03:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogAttendanceRealization generated by hbm2java
 */
@Entity
@Table(name="log_wt_attendance_realization"
    ,catalog="hrm"
)
public class LogWtAttendanceRealization  implements java.io.Serializable {


     private int id;
     private Long empDataId;
     private String empNik;
     private String empName;
     private String empJabatanCode;
     private String empJabatanName;
     private String empGolJab;
     private String empDepartementName;
     private Integer wtPeriodeId;
     private Date periodeDateStart;
     private Date periodeDateEnd;
     private Long wtGroupWorkingId;
     private String wtGroupWorkingName;
     private Integer attendanceDaysSchedule;
     private Integer attendanceDaysPresent;
     private Integer leave;
     private Float overtime;
     private Float permit;
     private Integer sick;
      private Integer duty;
     private Date createdOn;
     private String createdBy;

    public LogWtAttendanceRealization() {
    }

	
    public LogWtAttendanceRealization(int id) {
        this.id = id;
    }
    public LogWtAttendanceRealization(int id, Long empDataId, String empNik, String empName, String empJabatanCode, String empJabatanName, String empGolJab, String empDepartementName, Integer wtPeriodeId, Date periodeDateStart, Date periodeDateEnd, Long wtGroupWorkingId, String wtGroupWorkingName, Integer attendanceDaysSchedule, Integer attendanceDaysPresent, Integer leave, Float overtime, Float permit, Integer sick, Date createdOn, String createdBy) {
       this.id = id;
       this.empDataId = empDataId;
       this.empNik = empNik;
       this.empName = empName;
       this.empJabatanCode = empJabatanCode;
       this.empJabatanName = empJabatanName;
       this.empGolJab = empGolJab;
       this.empDepartementName = empDepartementName;
       this.wtPeriodeId = wtPeriodeId;
       this.periodeDateStart = periodeDateStart;
       this.periodeDateEnd = periodeDateEnd;
       this.wtGroupWorkingId = wtGroupWorkingId;
       this.wtGroupWorkingName = wtGroupWorkingName;
       this.attendanceDaysSchedule = attendanceDaysSchedule;
       this.attendanceDaysPresent = attendanceDaysPresent;
       this.leave = leave;
       this.overtime = overtime;
       this.permit = permit;
       this.sick = sick;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="emp_data_id")
    public Long getEmpDataId() {
        return this.empDataId;
    }
    
    public void setEmpDataId(Long empDataId) {
        this.empDataId = empDataId;
    }

    
    @Column(name="emp_nik", length=45)
    public String getEmpNik() {
        return this.empNik;
    }
    
    public void setEmpNik(String empNik) {
        this.empNik = empNik;
    }

    
    @Column(name="emp_name", length=45)
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    
    @Column(name="emp_jabatan_code", length=45)
    public String getEmpJabatanCode() {
        return this.empJabatanCode;
    }
    
    public void setEmpJabatanCode(String empJabatanCode) {
        this.empJabatanCode = empJabatanCode;
    }

    
    @Column(name="emp_jabatan_name", length=45)
    public String getEmpJabatanName() {
        return this.empJabatanName;
    }
    
    public void setEmpJabatanName(String empJabatanName) {
        this.empJabatanName = empJabatanName;
    }

    
    @Column(name="emp_gol_jab", length=45)
    public String getEmpGolJab() {
        return this.empGolJab;
    }
    
    public void setEmpGolJab(String empGolJab) {
        this.empGolJab = empGolJab;
    }

    
    @Column(name="emp_departement_name", length=45)
    public String getEmpDepartementName() {
        return this.empDepartementName;
    }
    
    public void setEmpDepartementName(String empDepartementName) {
        this.empDepartementName = empDepartementName;
    }

    
    @Column(name="wt_periode_id")
    public Integer getWtPeriodeId() {
        return this.wtPeriodeId;
    }
    
    public void setWtPeriodeId(Integer wtPeriodeId) {
        this.wtPeriodeId = wtPeriodeId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="periode_date_start", length=10)
    public Date getPeriodeDateStart() {
        return this.periodeDateStart;
    }
    
    public void setPeriodeDateStart(Date periodeDateStart) {
        this.periodeDateStart = periodeDateStart;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="periode_date_end", length=10)
    public Date getPeriodeDateEnd() {
        return this.periodeDateEnd;
    }
    
    public void setPeriodeDateEnd(Date periodeDateEnd) {
        this.periodeDateEnd = periodeDateEnd;
    }

    
    @Column(name="wt_group_working_id")
    public Long getWtGroupWorkingId() {
        return this.wtGroupWorkingId;
    }
    
    public void setWtGroupWorkingId(Long wtGroupWorkingId) {
        this.wtGroupWorkingId = wtGroupWorkingId;
    }

    
    @Column(name="wt_group_working_name", length=45)
    public String getWtGroupWorkingName() {
        return this.wtGroupWorkingName;
    }
    
    public void setWtGroupWorkingName(String wtGroupWorkingName) {
        this.wtGroupWorkingName = wtGroupWorkingName;
    }

    
    @Column(name="attendance_days_schedule")
    public Integer getAttendanceDaysSchedule() {
        return this.attendanceDaysSchedule;
    }
    
    public void setAttendanceDaysSchedule(Integer attendanceDaysSchedule) {
        this.attendanceDaysSchedule = attendanceDaysSchedule;
    }

    
    @Column(name="attendance_days_present")
    public Integer getAttendanceDaysPresent() {
        return this.attendanceDaysPresent;
    }
    
    public void setAttendanceDaysPresent(Integer attendanceDaysPresent) {
        this.attendanceDaysPresent = attendanceDaysPresent;
    }

    
    @Column(name="leave")
    public Integer getLeave() {
        return this.leave;
    }
    
    public void setLeave(Integer leave) {
        this.leave = leave;
    }

    
    @Column(name="overtime", precision=12, scale=0)
    public Float getOvertime() {
        return this.overtime;
    }
    
    public void setOvertime(Float overtime) {
        this.overtime = overtime;
    }

    
    @Column(name="permit", precision=12, scale=0)
    public Float getPermit() {
        return this.permit;
    }
    
    public void setPermit(Float permit) {
        this.permit = permit;
    }

    
    @Column(name="sick")
    public Integer getSick() {
        return this.sick;
    }
    
    public void setSick(Integer sick) {
        this.sick = sick;
    }
    
     @Column(name="duty")
    public Integer getDuty() {
        return this.duty;
    }
    
    public void setDuty(Integer duty) {
        this.duty = duty;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


