package com.inkubator.hrm.entity;
// Generated Oct 20, 2014 5:06:29 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MacineFingerUpload generated by hbm2java
 */
@Entity
@Table(name = "macine_finger_upload", catalog="hrm_payroll_backup"
)
public class MacineFingerUpload implements java.io.Serializable {

    private long id;
    private Integer version;
    private MecineFinger mecineFinger;
    private Integer fieldNo;
    private String fieldLabel;
    private String fieldType;
    private Integer fieldLen;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;
    private String description;

    public MacineFingerUpload() {
    }

    public MacineFingerUpload(long id) {
        this.id = id;
    }

    public MacineFingerUpload(long id, MecineFinger mecineFinger, Integer fieldNo, String fieldLabel, String fieldType, Integer fieldLen, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
        this.id = id;
        this.mecineFinger = mecineFinger;
        this.fieldNo = fieldNo;
        this.fieldLabel = fieldLabel;
        this.fieldType = fieldType;
        this.fieldLen = fieldLen;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mesin_id")
    public MecineFinger getMecineFinger() {
        return this.mecineFinger;
    }

    public void setMecineFinger(MecineFinger mecineFinger) {
        this.mecineFinger = mecineFinger;
    }

    @Column(name = "field_no")
    public Integer getFieldNo() {
        return this.fieldNo;
    }

    public void setFieldNo(Integer fieldNo) {
        this.fieldNo = fieldNo;
    }

    @Column(name = "field_label", length = 45)
    public String getFieldLabel() {
        return this.fieldLabel;
    }

    public void setFieldLabel(String fieldLabel) {
        this.fieldLabel = fieldLabel;
    }

    @Column(name = "field_type", length = 45)
    public String getFieldType() {
        return this.fieldType;
    }

    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    @Column(name = "field_len")
    public Integer getFieldLen() {
        return this.fieldLen;
    }

    public void setFieldLen(Integer fieldLen) {
        this.fieldLen = fieldLen;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Column(name = "description", length = 65535, columnDefinition = "Text")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
