package com.inkubator.hrm.entity;
// Generated Mar 12, 2015 4:24:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * OhsaEmpInvolve generated by hbm2java
 */
@Entity
@Table(name="ohsa_emp_involve"
    ,catalog="hrm_payroll_backup"
)
public class OhsaEmpInvolve  implements java.io.Serializable {


     private long id;
     private Integer version;
//   private Long ohsaIncidentId;
     private OhsaIncident ohsaIncident;
     private EmpData empData;
     private Date createdOn;
     private String createdBy;

    public OhsaEmpInvolve() {
    }

	
    public OhsaEmpInvolve(long id) {
        this.id = id;
    }
    public OhsaEmpInvolve(long id, OhsaIncident ohsaIncident, EmpData empData, Date createdOn, String createdBy) {
       this.id = id;
       this.ohsaIncident = ohsaIncident;
       this.empData = empData;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ohsa_incident_id")
    public OhsaIncident getOhsaIncident() {
        return this.ohsaIncident;
    }
    
    public void setOhsaIncident(OhsaIncident ohsaIncident) {
        this.ohsaIncident = ohsaIncident;
    }
    
//    @Column(name="emp_data_id")
//    public Long getEmpDataId() {
//        return this.empDataId;
//    }
//    
//    public void setEmpDataId(Long empDataId) {
//        this.empDataId = empDataId;
//    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_data_id")
    public EmpData getEmpData() {
        return empData;
    }

    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }
    
    

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


