package com.inkubator.hrm.entity;
// Generated Jun 17, 2014 4:36:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * OrganizationLetter generated by hbm2java
 */
@Entity
@Table(name="organization_letter"
    ,catalog="hrm_payroll"
    , uniqueConstraints = @UniqueConstraint(columnNames="letter_number") 
)
public class OrganizationLetter  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String letterNumber;
     private Date letterDate;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public OrganizationLetter() {
    }

	
    public OrganizationLetter(long id) {
        this.id = id;
    }
    public OrganizationLetter(long id, String letterNumber, Date letterDate, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.id = id;
       this.letterNumber = letterNumber;
       this.letterDate = letterDate;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="letter_number", unique=true, length=60)
    public String getLetterNumber() {
        return this.letterNumber;
    }
    
    public void setLetterNumber(String letterNumber) {
        this.letterNumber = letterNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="letter_date", length=10)
    public Date getLetterDate() {
        return this.letterDate;
    }
    
    public void setLetterDate(Date letterDate) {
        this.letterDate = letterDate;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


