package com.inkubator.hrm.entity;
// Generated Apr 8, 2015 12:54:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * OrgJobFamilyLevel generated by hbm2java
 */
@Entity
@Table(name="org_job_family_level"
    ,catalog="hrm"
)
public class OrgJobFamilyLevel  implements java.io.Serializable {


     private long id;
     private Integer version;
     private GolonganJabatan golonganJabatan;
     private KlasifikasiKerja klasifikasiKerja;
     private PaCompetencies paCompetencies;
     private Pangkat pangkat;
     private Date createdOn;
     private Integer pointScore;
     private Date updatedOn;
     private String createdBy;
     private String updatedBy;

    public OrgJobFamilyLevel() {
    }

	
    public OrgJobFamilyLevel(long id) {
        this.id = id;
    }
    public OrgJobFamilyLevel(long id, GolonganJabatan golonganJabatan, KlasifikasiKerja klasifikasiKerja, PaCompetencies paCompetencies, Pangkat pangkat, Date createdOn, Integer pointScore, Date updatedOn, String createdBy, String updatedBy) {
       this.id = id;
       this.golonganJabatan = golonganJabatan;
       this.klasifikasiKerja = klasifikasiKerja;
       this.paCompetencies = paCompetencies;
       this.pangkat = pangkat;
       this.createdOn = createdOn;
       this.pointScore = pointScore;
       this.updatedOn = updatedOn;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gol_jabatan_id")
    public GolonganJabatan getGolonganJabatan() {
        return this.golonganJabatan;
    }
    
    public void setGolonganJabatan(GolonganJabatan golonganJabatan) {
        this.golonganJabatan = golonganJabatan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_family_id")
    public KlasifikasiKerja getKlasifikasiKerja() {
        return this.klasifikasiKerja;
    }
    
    public void setKlasifikasiKerja(KlasifikasiKerja klasifikasiKerja) {
        this.klasifikasiKerja = klasifikasiKerja;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="competency_id")
    public PaCompetencies getPaCompetencies() {
        return this.paCompetencies;
    }
    
    public void setPaCompetencies(PaCompetencies paCompetencies) {
        this.paCompetencies = paCompetencies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pangkat_id")
    public Pangkat getPangkat() {
        return this.pangkat;
    }
    
    public void setPangkat(Pangkat pangkat) {
        this.pangkat = pangkat;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="point_score")
    public Integer getPointScore() {
        return this.pointScore;
    }
    
    public void setPointScore(Integer pointScore) {
        this.pointScore = pointScore;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


