package com.inkubator.hrm.entity;
// Generated Apr 7, 2015 3:50:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * OrgKlasifikasiJobFamily generated by hbm2java
 */
@Entity
@Table(name="org_klasifikasi_job_family"
    ,catalog="hrm"
)
public class OrgKlasifikasiJobFamily  implements java.io.Serializable {


     private OrgKlasifikasiJobFamilyId id;
     private Integer version;
     private GolonganJabatan golonganJabatan;
     private KlasifikasiKerja klasifikasiKerja;
     private Date createdOn;
     private String createdBy;

    public OrgKlasifikasiJobFamily() {
    }

	
    public OrgKlasifikasiJobFamily(OrgKlasifikasiJobFamilyId id, GolonganJabatan golonganJabatan, KlasifikasiKerja klasifikasiKerja) {
        this.id = id;
        this.golonganJabatan = golonganJabatan;
        this.klasifikasiKerja = klasifikasiKerja;
    }
    public OrgKlasifikasiJobFamily(OrgKlasifikasiJobFamilyId id, GolonganJabatan golonganJabatan, KlasifikasiKerja klasifikasiKerja, Date createdOn, String createdBy) {
       this.id = id;
       this.golonganJabatan = golonganJabatan;
       this.klasifikasiKerja = klasifikasiKerja;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="golonganJabatanId", column=@Column(name="golongan_jabatan_id", nullable=false) ), 
        @AttributeOverride(name="klasifikasiKerjaId", column=@Column(name="klasifikasi_kerja_id", nullable=false) ) } )
    public OrgKlasifikasiJobFamilyId getId() {
        return this.id;
    }
    
    public void setId(OrgKlasifikasiJobFamilyId id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="golongan_jabatan_id", nullable=false, insertable=false, updatable=false)
    public GolonganJabatan getGolonganJabatan() {
        return this.golonganJabatan;
    }
    
    public void setGolonganJabatan(GolonganJabatan golonganJabatan) {
        this.golonganJabatan = golonganJabatan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="klasifikasi_kerja_id", nullable=false, insertable=false, updatable=false)
    public KlasifikasiKerja getKlasifikasiKerja() {
        return this.klasifikasiKerja;
    }
    
    public void setKlasifikasiKerja(KlasifikasiKerja klasifikasiKerja) {
        this.klasifikasiKerja = klasifikasiKerja;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


