package com.inkubator.hrm.entity;
// Generated Oct 3, 2014 11:07:50 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OverTimeDistribution generated by hbm2java
 */
@Entity
@Table(name = "over_time_distribution", catalog = "hrm"
)
public class OverTimeDistribution implements java.io.Serializable {

    private OverTimeDistributionId id;
    private EmpData empData;
    private WtOverTime wtOverTime;
    private String description;

    public OverTimeDistribution() {
    }

    public OverTimeDistribution(OverTimeDistributionId id, EmpData empData, WtOverTime wtOverTime) {
        this.id = id;
        this.empData = empData;
        this.wtOverTime = wtOverTime;
    }

    public OverTimeDistribution(OverTimeDistributionId id, EmpData empData, WtOverTime wtOverTime, String description) {
        this.id = id;
        this.empData = empData;
        this.wtOverTime = wtOverTime;
        this.description = description;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "overtaimeId", column = @Column(name = "overtaime_id", nullable = false)),
        @AttributeOverride(name = "empId", column = @Column(name = "emp_id", nullable = false))})
    public OverTimeDistributionId getId() {
        return this.id;
    }

    public void setId(OverTimeDistributionId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_id", nullable = false, insertable = false, updatable = false)
    public EmpData getEmpData() {
        return this.empData;
    }

    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "overtaime_id", nullable = false, insertable = false, updatable = false)
    public WtOverTime getWtOverTime() {
        return this.wtOverTime;
    }

    public void setWtOverTime(WtOverTime wtOverTime) {
        this.wtOverTime = wtOverTime;
    }

    @Column(name = "description", length = 45)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
