package com.inkubator.hrm.entity;
// Generated Apr 8, 2015 12:54:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PaCompetencies generated by hbm2java
 */
@Entity
@Table(name="pa_competencies"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class PaCompetencies  implements java.io.Serializable {


     private long id;
     private Integer version;
     private int typeOfCompetency;
     private Integer modelCompentency;
     private String code;
     private String name;
     private String description;
     private Date createdOn;
     private String createdBy;
     private String updatedBy;
     private Date updatedOn;
     private Boolean isActive;
     private Set<PaCompetencyPoint> paCompetencyPoints = new HashSet<PaCompetencyPoint>(0);
     private Set<OrgJobFamilyLevel> orgJobFamilyLevels = new HashSet<OrgJobFamilyLevel>(0);

    public PaCompetencies() {
    }

	
    public PaCompetencies(long id, int typeOfCompetency, String code, String name) {
        this.id = id;
        this.typeOfCompetency = typeOfCompetency;
        this.code = code;
        this.name = name;
    }
    public PaCompetencies(long id, int typeOfCompetency, Integer modelCompentency, String code, String name, String description, Date createdOn, String createdBy, String updatedBy, Date updatedOn, Boolean isActive, Set<PaCompetencyPoint> paCompetencyPoints, Set<OrgJobFamilyLevel> orgJobFamilyLevels) {
       this.id = id;
       this.typeOfCompetency = typeOfCompetency;
       this.modelCompentency = modelCompentency;
       this.code = code;
       this.name = name;
       this.description = description;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.isActive = isActive;
       this.paCompetencyPoints = paCompetencyPoints;
       this.orgJobFamilyLevels = orgJobFamilyLevels;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="type_of_competency", nullable=false)
    public int getTypeOfCompetency() {
        return this.typeOfCompetency;
    }
    
    public void setTypeOfCompetency(int typeOfCompetency) {
        this.typeOfCompetency = typeOfCompetency;
    }

    
    @Column(name="model_compentency")
    public Integer getModelCompentency() {
        return this.modelCompentency;
    }
    
    public void setModelCompentency(Integer modelCompentency) {
        this.modelCompentency = modelCompentency;
    }

    
    @Column(name="code", unique=true, nullable=false, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paCompetencies")
    public Set<PaCompetencyPoint> getPaCompetencyPoints() {
        return this.paCompetencyPoints;
    }
    
    public void setPaCompetencyPoints(Set<PaCompetencyPoint> paCompetencyPoints) {
        this.paCompetencyPoints = paCompetencyPoints;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paCompetencies")
    public Set<OrgJobFamilyLevel> getOrgJobFamilyLevels() {
        return this.orgJobFamilyLevels;
    }
    
    public void setOrgJobFamilyLevels(Set<OrgJobFamilyLevel> orgJobFamilyLevels) {
        this.orgJobFamilyLevels = orgJobFamilyLevels;
    }




}


