package com.inkubator.hrm.entity;
// Generated Apr 8, 2015 12:54:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PaCompetencyPoint generated by hbm2java
 */
@Entity
@Table(name="pa_competency_point"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class PaCompetencyPoint  implements java.io.Serializable {


     private long id;
     private Integer version;
     private PaCompetencies paCompetencies;
     private String code;
     private String name;
     private int competencyPointScore;
     private String description;
     private Date createdOn;
     private String createdBy;
     private String updatedBy;
     private Date updatedOn;

    public PaCompetencyPoint() {
    }

	
    public PaCompetencyPoint(long id, PaCompetencies paCompetencies, String code, String name, int competencyPointScore) {
        this.id = id;
        this.paCompetencies = paCompetencies;
        this.code = code;
        this.name = name;
        this.competencyPointScore = competencyPointScore;
    }
    public PaCompetencyPoint(long id, PaCompetencies paCompetencies, String code, String name, int competencyPointScore, String description, Date createdOn, String createdBy, String updatedBy, Date updatedOn) {
       this.id = id;
       this.paCompetencies = paCompetencies;
       this.code = code;
       this.name = name;
       this.competencyPointScore = competencyPointScore;
       this.description = description;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="competency_id", nullable=false)
    public PaCompetencies getPaCompetencies() {
        return this.paCompetencies;
    }
    
    public void setPaCompetencies(PaCompetencies paCompetencies) {
        this.paCompetencies = paCompetencies;
    }

    
    @Column(name="code", unique=true, nullable=false, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="competency_point_score", nullable=false)
    public int getCompetencyPointScore() {
        return this.competencyPointScore;
    }
    
    public void setCompetencyPointScore(int competencyPointScore) {
        this.competencyPointScore = competencyPointScore;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


