package com.inkubator.hrm.entity;
// Generated Jun 17, 2014 4:36:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Pangkat generated by hbm2java
 */
@Entity
@Table(name="pangkat"
    ,catalog="hrm_personalia"
    , uniqueConstraints = @UniqueConstraint(columnNames="pangkat_code") 
)
public class Pangkat  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String pangkatCode;
     private String pangkatName;
//     private Integer level;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private Set<GolonganJabatan> golonganJabatans = new HashSet<GolonganJabatan>(0);

    public Pangkat() {
    }

	
    public Pangkat(long id) {
        this.id = id;
    }
    public Pangkat(long id, String pangkatCode, String pangkatName, Integer level, String createdBy, Date createdOn, String updatedBy, Date updatedOn, Set<GolonganJabatan> golonganJabatans) {
       this.id = id;
       this.pangkatCode = pangkatCode;
       this.pangkatName = pangkatName;
//       this.level = level;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.golonganJabatans = golonganJabatans;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="pangkat_code", unique=true, length=8)
    public String getPangkatCode() {
        return this.pangkatCode;
    }
    
    public void setPangkatCode(String pangkatCode) {
        this.pangkatCode = pangkatCode;
    }

    
    @Column(name="pangkat_name", length=60)
    public String getPangkatName() {
        return this.pangkatName;
    }
    
    public void setPangkatName(String pangkatName) {
        this.pangkatName = pangkatName;
    }

    
//    @Column(name="level")
//    public Integer getLevel() {
//        return this.level;
//    }
//    
//    public void setLevel(Integer level) {
//        this.level = level;
//    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pangkat")
    public Set<GolonganJabatan> getGolonganJabatans() {
        return this.golonganJabatans;
    }
    
    public void setGolonganJabatans(Set<GolonganJabatan> golonganJabatans) {
        this.golonganJabatans = golonganJabatans;
    }




}


