package com.inkubator.hrm.entity;
// Generated Dec 16, 2014 4:30:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PayReceiverBankAccount generated by hbm2java
 */
@Entity
@Table(name="pay_receiver_bank_account"
    ,catalog="hrm"
)
public class PayReceiverBankAccount  implements java.io.Serializable {


     private long id;
     private Integer version;
     private BioBankAccount bioBankAccount;
     private EmpData empData;
     private Double persen;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public PayReceiverBankAccount() {
    }

	
    public PayReceiverBankAccount(long id) {
        this.id = id;
    }
    public PayReceiverBankAccount(long id, BioBankAccount bioBankAccount, EmpData empData, Double persen, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.id = id;
       this.bioBankAccount = bioBankAccount;
       this.empData = empData;
       this.persen = persen;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bank_account_id")
    public BioBankAccount getBioBankAccount() {
        return this.bioBankAccount;
    }
    
    public void setBioBankAccount(BioBankAccount bioBankAccount) {
        this.bioBankAccount = bioBankAccount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_data_id")
    public EmpData getEmpData() {
        return this.empData;
    }
    
    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }

    
    @Column(name="persen", precision=22, scale=0)
    public Double getPersen() {
        return this.persen;
    }
    
    public void setPersen(Double persen) {
        this.persen = persen;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


