package com.inkubator.hrm.entity;
// Generated Aug 11, 2014 1:21:52 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PaySalaryJurnal generated by hbm2java
 */
@Entity
@Table(name="pay_salary_jurnal"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class PaySalaryJurnal  implements java.io.Serializable {


     private long id;
     private Integer version;
     private CostCenter costCenter;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private String code;
     private String name;
     private Integer typeJurnal;
     private Integer modelJurnal;
     private String description;

    public PaySalaryJurnal() {
    }

	
    public PaySalaryJurnal(long id, CostCenter costCenter) {
        this.id = id;
        this.costCenter = costCenter;
    }
    public PaySalaryJurnal(long id, CostCenter costCenter, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String code, String name, String description) {
       this.id = id;
       this.costCenter = costCenter;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.code = code;
       this.name = name;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cost_center_id", nullable=false)
    public CostCenter getCostCenter() {
        return this.costCenter;
    }
    
    public void setCostCenter(CostCenter costCenter) {
        this.costCenter = costCenter;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="code", unique=true, length=8)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535, columnDefinition="Text")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="type_jurnal", length=1)
    public Integer getTypeJurnal() {
        return typeJurnal;
    }

    public void setTypeJurnal(Integer typeJurnal) {
        this.typeJurnal = typeJurnal;
    }

    @Column(name="model_jurnal", length=1)
    public Integer getModelJurnal() {
        return modelJurnal;
    }

    public void setModelJurnal(Integer modelJurnal) {
        this.modelJurnal = modelJurnal;
    }




}


