package com.inkubator.hrm.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PaySalaryComponent generated by hbm2java
 */
@Entity
@Table(name="pay_temp_upload_data", catalog="hrm_payroll", uniqueConstraints = @UniqueConstraint(columnNames = {"emp_data_id","pay_salary_component_id"}))
public class PayTempUploadData  implements java.io.Serializable {


     private Long id;
     private Integer version;
     private PaySalaryComponent paySalaryComponent;
     private EmpData empData;
     private Double nominalValue;
     private String pathUpload;     
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public PayTempUploadData() {
    }
	
    public PayTempUploadData(Long id) {
        this.id = id;
    }
   
    @Id 
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pay_salary_component_id", nullable = false)
    public PaySalaryComponent getPaySalaryComponent() {
		return paySalaryComponent;
	}

	public void setPaySalaryComponent(PaySalaryComponent paySalaryComponent) {
		this.paySalaryComponent = paySalaryComponent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_data_id", nullable = false)
	public EmpData getEmpData() {
		return empData;
	}

	public void setEmpData(EmpData empData) {
		this.empData = empData;
	}

	@Column(name="nominal_value", nullable = false)
	public Double getNominalValue() {
		return nominalValue;
	}

	public void setNominalValue(Double nominalValue) {
		this.nominalValue = nominalValue;
	}

	@Column(name = "upload_path", length = 255)
	public String getPathUpload() {
		return pathUpload;
	}

	public void setPathUpload(String pathUpload) {
		this.pathUpload = pathUpload;
	}

	@Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

}


