package com.inkubator.hrm.entity;
// Generated Dec 5, 2014 9:54:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PayTempKalkulasi generated by hbm2java
 */
@Entity
@Table(name="pay_temp_kalkulasi"
    ,catalog="hrm"
)
public class PayTempKalkulasi  implements java.io.Serializable {


     private long id;
     private Integer version;
     private EmpData empData;
     private PaySalaryComponent paySalaryComponent;
     private Double nominal;
     private Date createdOn;
     private String createdBy;
     private String updatedBy;
     private Date updatedOn;

    public PayTempKalkulasi() {
    }

	
    public PayTempKalkulasi(long id) {
        this.id = id;
    }
    public PayTempKalkulasi(long id, EmpData empData, PaySalaryComponent paySalaryComponent, Double nominal, Date createdOn, String createdBy, String updatedBy, Date updatedOn) {
       this.id = id;
       this.empData = empData;
       this.paySalaryComponent = paySalaryComponent;
       this.nominal = nominal;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_data_id")
    public EmpData getEmpData() {
        return this.empData;
    }
    
    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pay_salary_component_id")
    public PaySalaryComponent getPaySalaryComponent() {
        return this.paySalaryComponent;
    }
    
    public void setPaySalaryComponent(PaySalaryComponent paySalaryComponent) {
        this.paySalaryComponent = paySalaryComponent;
    }

    
    @Column(name="nominal", precision=22, scale=0)
    public Double getNominal() {
        return this.nominal;
    }
    
    public void setNominal(Double nominal) {
        this.nominal = nominal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


