package com.inkubator.hrm.entity;

// Generated Nov 10, 2014 2:26:19 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

/**
 * PermitDistribution generated by hbm2java
 */
@Entity
@Table(name = "permit_distribution", catalog = "hrm_payroll_backup")
public class PermitDistribution implements java.io.Serializable {

	private long id;
	private Integer version;
	private EmpData empData;
	private PermitClassification permitClassification;
	private Double balance;
	private Date endDate;
	private Date startDate;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private Boolean isDisabled;
	private Set<NeracaPermit> neracaPermits = new HashSet<NeracaPermit>(0);

	public PermitDistribution() {
	}

	public PermitDistribution(long id, EmpData empData, PermitClassification permitClassification, double balance) {
		this.id = id;
		this.empData = empData;
		this.permitClassification = permitClassification;
		this.balance = balance;
	}

	public PermitDistribution(long id, EmpData empData, PermitClassification permitClassification, double balance, String createdBy, Date createdOn, String updatedBy, Date updatedOn,
			Set<NeracaPermit> neracaPermits) {
		this.id = id;
		this.empData = empData;
		this.permitClassification = permitClassification;
		this.balance = balance;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.neracaPermits = neracaPermits;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emp_data_id", nullable = false)
	public EmpData getEmpData() {
		return this.empData;
	}

	public void setEmpData(EmpData empData) {
		this.empData = empData;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permit_classification_id", nullable = false)
	public PermitClassification getPermitClassification() {
		return this.permitClassification;
	}

	public void setPermitClassification(PermitClassification permitClassification) {
		this.permitClassification = permitClassification;
	}

	@Column(name = "balance", nullable = false, precision = 22, scale = 0)
	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permitDistribution", cascade=CascadeType.REMOVE)
	public Set<NeracaPermit> getNeracaPermits() {
		return this.neracaPermits;
	}

	public void setNeracaPermits(Set<NeracaPermit> neracaPermits) {
		this.neracaPermits = neracaPermits;
	}

	@Transient
	public Boolean getIsDisabled() {
		return isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}
}
