package com.inkubator.hrm.entity;

// Generated Mar 13, 2015 9:01:09 AM by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RecruitVacancyAdvertisement generated by hbm2java
 */
@Entity
@Table(name = "recruit_vacancy_advertisement", catalog = "hrm")
public class RecruitVacancyAdvertisement implements java.io.Serializable {

    private Long id;
    private Integer version;
    private String vacancyAdvCode;
    private Date effectiveDate;
    private RecruitAdvertisementMedia advertisementMedia;
    private String approvalActivityNumber;
    private Integer applicationStatus;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;
    private Set<RecruitVacancyAdvertisementDetail> recruitVacancyAdvertisementDetails = new HashSet<RecruitVacancyAdvertisementDetail>(0);

    public RecruitVacancyAdvertisement(){
    	
    }
    
    public RecruitVacancyAdvertisement(Long id) {
        this.id = id;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "recruit_vacancy_advertisement_seq_gen")
    @SequenceGenerator(name = "recruit_vacancy_advertisement_seq_gen", sequenceName = "RECRUIT_VACANCY_ADVERTISEMENT_SEQ")
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
        
    @Column(name = "vacancy_adv_code", unique = true, nullable = false, length = 45)
    public String getVacancyAdvCode() {
		return vacancyAdvCode;
	}

	public void setVacancyAdvCode(String vacancyAdvCode) {
		this.vacancyAdvCode = vacancyAdvCode;
	}

	@Temporal(TemporalType.DATE)
    @Column(name = "effective_date", length = 19, nullable = false)
	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "advertisement_media_id", nullable = false)
	public RecruitAdvertisementMedia getAdvertisementMedia() {
		return advertisementMedia;
	}

	public void setAdvertisementMedia(RecruitAdvertisementMedia advertisementMedia) {
		this.advertisementMedia = advertisementMedia;
	}

    @Column(name = "application_status", nullable = false)
    public Integer getApplicationStatus() {
        return applicationStatus;
    }

    public void setApplicationStatus(Integer applicationStatus) {
        this.applicationStatus = applicationStatus;
    }

    @Column(name = "approval_activity_number", length = 45, unique = true)
    public String getApprovalActivityNumber() {
        return approvalActivityNumber;
    }

    public void setApprovalActivityNumber(String approvalActivityNumber) {
        this.approvalActivityNumber = approvalActivityNumber;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

	@OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.LAZY, mappedBy = "vacancyAdvertisement")
	public Set<RecruitVacancyAdvertisementDetail> getRecruitVacancyAdvertisementDetails() {
		return recruitVacancyAdvertisementDetails;
	}

	public void setRecruitVacancyAdvertisementDetails(Set<RecruitVacancyAdvertisementDetail> recruitVacancyAdvertisementDetails) {
		this.recruitVacancyAdvertisementDetails = recruitVacancyAdvertisementDetails;
	}
	
	
    
    

}
