package com.inkubator.hrm.entity;
// Generated Sep 16, 2015 3:25:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecruitMppApplyDetailTime generated by hbm2java
 */
@Entity
@Table(name="recruit_mpp_apply_detail_time"
    ,catalog="hrm"
)
public class RecruitMppApplyDetailTime  implements java.io.Serializable {


     private long id;
     private RecruitMppApplyDetail recruitMppApplyDetail;
     private Date mppMonthApply;
     private Integer planningPerson;
     private String createdBy;
     private Date createdOn;

    public RecruitMppApplyDetailTime() {
    }

	
    public RecruitMppApplyDetailTime(long id) {
        this.id = id;
    }
    public RecruitMppApplyDetailTime(long id, RecruitMppApplyDetail recruitMppApplyDetail, Date mppMonthApply, Integer planningPerson) {
       this.id = id;
       this.recruitMppApplyDetail = recruitMppApplyDetail;
       this.mppMonthApply = mppMonthApply;
       this.planningPerson = planningPerson;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="recruit_mpp_apply_detail_id")
    public RecruitMppApplyDetail getRecruitMppApplyDetail() {
        return this.recruitMppApplyDetail;
    }
    
    public void setRecruitMppApplyDetail(RecruitMppApplyDetail recruitMppApplyDetail) {
        this.recruitMppApplyDetail = recruitMppApplyDetail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mpp_month_apply", length=10)
    public Date getMppMonthApply() {
        return this.mppMonthApply;
    }
    
    public void setMppMonthApply(Date mppMonthApply) {
        this.mppMonthApply = mppMonthApply;
    }

    
    @Column(name="planning_person")
    public Integer getPlanningPerson() {
        return this.planningPerson;
    }
    
    public void setPlanningPerson(Integer planningPerson) {
        this.planningPerson = planningPerson;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }


}


