package com.inkubator.hrm.entity;
// Generated Oct 23, 2015 2:26:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RecruitCommChannels generated by hbm2java
 */
@Entity
@Table(name="recruit_comm_channels"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="channel_name") 
)
public class RecruitCommChannels  implements java.io.Serializable {


     private long id;
     private String channelName;
     private Date createdOn;
     private String createdBy;
     private Set<RecruitLetterComChannel> recruitLetterComChannels = new HashSet<RecruitLetterComChannel>(0);

    public RecruitCommChannels() {
    }

	
    public RecruitCommChannels(long id) {
        this.id = id;
    }
    public RecruitCommChannels(long id, String channelName, Date createdOn, String createdBy, Set<RecruitLetterComChannel> recruitLetterComChannels) {
       this.id = id;
       this.channelName = channelName;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.recruitLetterComChannels = recruitLetterComChannels;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="channel_name", unique=true, length=45)
    public String getChannelName() {
        return this.channelName;
    }
    
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recruitCommChannels")
    public Set<RecruitLetterComChannel> getRecruitLetterComChannels() {
        return this.recruitLetterComChannels;
    }
    
    public void setRecruitLetterComChannels(Set<RecruitLetterComChannel> recruitLetterComChannels) {
        this.recruitLetterComChannels = recruitLetterComChannels;
    }



}


