package com.inkubator.hrm.entity;
// Generated Oct 26, 2015 11:22:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RecruitSelectionApplicantSchedulleDetail generated by hbm2java
 */
@Entity
@Table(name="recruit_selection_applicant_schedulle_detail"
    ,catalog="hrm"
)
public class RecruitSelectionApplicantSchedulleDetail  implements java.io.Serializable {


     private long id;
     private Integer version;
     private EmpData empData;
     private RecruitSelectionApplicantInitial recruitSelectionApplicantInitial;
     private RecruitSelectionApplicantSchedulle recruitSelectionApplicantSchedulle;
     private RecruitmenSelectionSeriesDetail selectionSeriesDetail;
     private Date schdulleDate;
     private Date schdulleTimeStart;
     private Date schedulleTimeEnd;
     private Date createdOn;
     private String createdBy;
     private Date updatedOn;
     private String updatedBy;
     private String room;
     private String notes;

    public RecruitSelectionApplicantSchedulleDetail() {
    }

	
    public RecruitSelectionApplicantSchedulleDetail(long id) {
        this.id = id;
    }
    public RecruitSelectionApplicantSchedulleDetail(long id, EmpData empData, RecruitSelectionApplicantInitial recruitSelectionApplicantInitial, RecruitSelectionApplicantSchedulle recruitSelectionApplicantSchedulle, Date schdulleDate, Date schdulleTimeStart, Date schedulleTimeEnd, Date createdOn, String createdBy, Date updatedOn, String updatedBy, String room, String notes) {
       this.id = id;
       this.empData = empData;
       this.recruitSelectionApplicantInitial = recruitSelectionApplicantInitial;
       this.recruitSelectionApplicantSchedulle = recruitSelectionApplicantSchedulle;
       this.schdulleDate = schdulleDate;
       this.schdulleTimeStart = schdulleTimeStart;
       this.schedulleTimeEnd = schedulleTimeEnd;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedOn = updatedOn;
       this.updatedBy = updatedBy;
       this.room = room;
       this.notes = notes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pic_emp_id")
    public EmpData getEmpData() {
        return this.empData;
    }
    
    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="initial_id")
    public RecruitSelectionApplicantInitial getRecruitSelectionApplicantInitial() {
        return this.recruitSelectionApplicantInitial;
    }
    
    public void setRecruitSelectionApplicantInitial(RecruitSelectionApplicantInitial recruitSelectionApplicantInitial) {
        this.recruitSelectionApplicantInitial = recruitSelectionApplicantInitial;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="schedulle_id")
    public RecruitSelectionApplicantSchedulle getRecruitSelectionApplicantSchedulle() {
        return this.recruitSelectionApplicantSchedulle;
    }
    
    public void setRecruitSelectionApplicantSchedulle(RecruitSelectionApplicantSchedulle recruitSelectionApplicantSchedulle) {
        this.recruitSelectionApplicantSchedulle = recruitSelectionApplicantSchedulle;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="selection_series_detail_id")
    public RecruitmenSelectionSeriesDetail getSelectionSeriesDetail() {
		return selectionSeriesDetail;
	}

	public void setSelectionSeriesDetail(RecruitmenSelectionSeriesDetail selectionSeriesDetail) {
		this.selectionSeriesDetail = selectionSeriesDetail;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="schdulle_date", length=10)
    public Date getSchdulleDate() {
        return this.schdulleDate;
    }
    
    public void setSchdulleDate(Date schdulleDate) {
        this.schdulleDate = schdulleDate;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="schdulle_time_start", length=8)
    public Date getSchdulleTimeStart() {
        return this.schdulleTimeStart;
    }
    
    public void setSchdulleTimeStart(Date schdulleTimeStart) {
        this.schdulleTimeStart = schdulleTimeStart;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="schedulle_time_end", length=8)
    public Date getSchedulleTimeEnd() {
        return this.schedulleTimeEnd;
    }
    
    public void setSchedulleTimeEnd(Date schedulleTimeEnd) {
        this.schedulleTimeEnd = schedulleTimeEnd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    
    @Column(name="room", length=45)
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


