package com.inkubator.hrm.entity;

// Generated Mar 13, 2015 9:01:09 AM by Hibernate Tools 4.3.1
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * RecruitVacancyAdvertisementDetail generated by hbm2java
 */
@Entity
@Table(name = "recruit_vacancy_advertisement_detail", catalog = "hrm", uniqueConstraints = @UniqueConstraint(columnNames = {"vacancy_advertisement_id", "hire_apply_id"}))
public class RecruitVacancyAdvertisementDetail implements java.io.Serializable {

    private Long id;
    private Integer version;
    private Date publishStart;
    private Date publishEnd;
    private RecruitVacancyAdvertisement vacancyAdvertisement;
    private RecruitHireApply hireApply;
    private Double cost;
    private String description;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;
    

    public RecruitVacancyAdvertisementDetail() {
    	
    }
    
    public RecruitVacancyAdvertisementDetail(Long id) {
        this.id = id;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "recruit_vacancy_advertisement_detail_seq_gen")
    @SequenceGenerator(name = "recruit_vacancy_advertisement_detail_seq_gen", sequenceName = "RECRUIT_VACANCY_ADVERTISEMENT_DETAIL_SEQ")
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }    
    
    @Temporal(TemporalType.DATE)
    @Column(name = "publish_start", length = 19, nullable = false)    
    public Date getPublishStart() {
		return publishStart;
	}

	public void setPublishStart(Date publishStart) {
		this.publishStart = publishStart;
	}

	@Temporal(TemporalType.DATE)
    @Column(name = "publish_end", length = 19, nullable = false)
	public Date getPublishEnd() {
		return publishEnd;
	}

	public void setPublishEnd(Date publishEnd) {
		this.publishEnd = publishEnd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vacancy_advertisement_id", nullable = false)
	public RecruitVacancyAdvertisement getVacancyAdvertisement() {
		return vacancyAdvertisement;
	}

	public void setVacancyAdvertisement(RecruitVacancyAdvertisement vacancyAdvertisement) {
		this.vacancyAdvertisement = vacancyAdvertisement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hire_apply_id", nullable = false)
	public RecruitHireApply getHireApply() {
		return hireApply;
	}

	public void setHireApply(RecruitHireApply hireApply) {
		this.hireApply = hireApply;
	}
	
	@Column(name = "cost", nullable =  false)
	public Double getCost() {
		return cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	@Column(name = "description", length = 65535, columnDefinition = "Text")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

}
