package com.inkubator.hrm.entity;
// Generated Oct 23, 2015 2:26:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RecruitLetterSelection generated by hbm2java
 */
@Entity
@Table(name="recruit_letter_selection"
    ,catalog="hrm"
)
public class RecruitLetterSelection  implements java.io.Serializable {


     private RecruitLetterSelectionId id;
     private Integer version;
     private RecruitLetters recruitLetters;
     private RecruitSelectionType recruitSelectionType;
     private Date createdOn;
     private String createdBy;

    public RecruitLetterSelection() {
    }

	
    public RecruitLetterSelection(RecruitLetterSelectionId id, RecruitLetters recruitLetters, RecruitSelectionType recruitSelectionType) {
        this.id = id;
        this.recruitLetters = recruitLetters;
        this.recruitSelectionType = recruitSelectionType;
    }
    public RecruitLetterSelection(RecruitLetterSelectionId id, RecruitLetters recruitLetters, RecruitSelectionType recruitSelectionType, Date createdOn, String createdBy) {
       this.id = id;
       this.recruitLetters = recruitLetters;
       this.recruitSelectionType = recruitSelectionType;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="letterId", column=@Column(name="letter_id", nullable=false) ), 
        @AttributeOverride(name="selectionTypeId", column=@Column(name="selection_type_id", nullable=false) ) } )
    public RecruitLetterSelectionId getId() {
        return this.id;
    }
    
    public void setId(RecruitLetterSelectionId id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="letter_id", nullable=false, insertable=false, updatable=false)
    public RecruitLetters getRecruitLetters() {
        return this.recruitLetters;
    }
    
    public void setRecruitLetters(RecruitLetters recruitLetters) {
        this.recruitLetters = recruitLetters;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="selection_type_id", nullable=false, insertable=false, updatable=false)
    public RecruitSelectionType getRecruitSelectionType() {
        return this.recruitSelectionType;
    }
    
    public void setRecruitSelectionType(RecruitSelectionType recruitSelectionType) {
        this.recruitSelectionType = recruitSelectionType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


