package com.inkubator.hrm.entity;
// Generated Apr 15, 2015 10:42:07 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecruitSelectionTypeField generated by hbm2java
 */
@Entity
@Table(name="recruit_selection_type_field"
    ,catalog="hrm"
)
public class RecruitSelectionTypeField  implements java.io.Serializable {


     private RecruitSelectionTypeFieldId id;
     private RecruitDynamicField recruitDynamicField;
     private RecruitSelectionType recruitSelectionType;
     private String fieldNewLabel;

    public RecruitSelectionTypeField() {
    }

	
    public RecruitSelectionTypeField(RecruitSelectionTypeFieldId id, RecruitDynamicField recruitDynamicField, RecruitSelectionType recruitSelectionType) {
        this.id = id;
        this.recruitDynamicField = recruitDynamicField;
        this.recruitSelectionType = recruitSelectionType;
    }
    public RecruitSelectionTypeField(RecruitSelectionTypeFieldId id, RecruitDynamicField recruitDynamicField, RecruitSelectionType recruitSelectionType, String fieldNewLabel) {
       this.id = id;
       this.recruitDynamicField = recruitDynamicField;
       this.recruitSelectionType = recruitSelectionType;
       this.fieldNewLabel = fieldNewLabel;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="selectionTypeId", column=@Column(name="selection_type_id", nullable=false) ), 
        @AttributeOverride(name="dynamicFieldId", column=@Column(name="dynamic_field_id", nullable=false) ) } )
    public RecruitSelectionTypeFieldId getId() {
        return this.id;
    }
    
    public void setId(RecruitSelectionTypeFieldId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dynamic_field_id", nullable=false, insertable=false, updatable=false)
    public RecruitDynamicField getRecruitDynamicField() {
        return this.recruitDynamicField;
    }
    
    public void setRecruitDynamicField(RecruitDynamicField recruitDynamicField) {
        this.recruitDynamicField = recruitDynamicField;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="selection_type_id", nullable=false, insertable=false, updatable=false)
    public RecruitSelectionType getRecruitSelectionType() {
        return this.recruitSelectionType;
    }
    
    public void setRecruitSelectionType(RecruitSelectionType recruitSelectionType) {
        this.recruitSelectionType = recruitSelectionType;
    }

    
    @Column(name="field_new_label", length=45)
    public String getFieldNewLabel() {
        return this.fieldNewLabel;
    }
    
    public void setFieldNewLabel(String fieldNewLabel) {
        this.fieldNewLabel = fieldNewLabel;
    }




}


