package com.inkubator.hrm.entity;
// Generated Jun 16, 2014 8:44:01 PM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecruitApplicantSpecList generated by hbm2java
 */
@Entity
@Table(name = "recruit_applicant_spec_list", catalog = "hrm"
)
public class RecruitApplicantSpecList implements java.io.Serializable {

    private ApplicantSpecListId id;
    private RecruitApplicant applicant;
    private OrgTypeOfSpecList orgTypeOfSpecList;
    private Date createdOn;
    private String createdBy;

    public RecruitApplicantSpecList() {
    }

    public RecruitApplicantSpecList(ApplicantSpecListId id, RecruitApplicant applicant, OrgTypeOfSpecList orgTypeOfSpecList) {
        this.id = id;
        this.applicant = applicant;
        this.orgTypeOfSpecList = orgTypeOfSpecList;
    }

    public RecruitApplicantSpecList(ApplicantSpecListId id, RecruitApplicant applicant, OrgTypeOfSpecList orgTypeOfSpecList, Date createdOn, String createdBy) {
    	this.id = id;
        this.applicant = applicant;
        this.orgTypeOfSpecList = orgTypeOfSpecList;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "applicantId", column = @Column(name = "applicant_id", nullable = false)),
        @AttributeOverride(name = "orgTypeOfSpecListId", column = @Column(name = "org_type_of_spec_list_id", nullable = false))})
    public ApplicantSpecListId getId() {
        return this.id;
    }

    public void setId(ApplicantSpecListId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "applicant_id", nullable = false, insertable = false, updatable = false)
    public RecruitApplicant getApplicant() {
		return applicant;
	}

	public void setApplicant(RecruitApplicant applicant) {
		this.applicant = applicant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_type_of_spec_list_id", nullable = false, insertable = false, updatable = false)
	public OrgTypeOfSpecList getOrgTypeOfSpecList() {
		return orgTypeOfSpecList;
	}

	public void setOrgTypeOfSpecList(OrgTypeOfSpecList orgTypeOfSpecList) {
		this.orgTypeOfSpecList = orgTypeOfSpecList;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

}
