package com.inkubator.hrm.entity;
// Generated Apr 15, 2015 10:42:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecruitSelectionTypeFieldId generated by hbm2java
 */
@Embeddable
public class RecruitSelectionTypeFieldId  implements java.io.Serializable {


     private long selectionTypeId;
     private long dynamicFieldId;

    public RecruitSelectionTypeFieldId() {
    }

    public RecruitSelectionTypeFieldId(long selectionTypeId, long dynamicFieldId) {
       this.selectionTypeId = selectionTypeId;
       this.dynamicFieldId = dynamicFieldId;
    }
   


    @Column(name="selection_type_id", nullable=false)
    public long getSelectionTypeId() {
        return this.selectionTypeId;
    }
    
    public void setSelectionTypeId(long selectionTypeId) {
        this.selectionTypeId = selectionTypeId;
    }


    @Column(name="dynamic_field_id", nullable=false)
    public long getDynamicFieldId() {
        return this.dynamicFieldId;
    }
    
    public void setDynamicFieldId(long dynamicFieldId) {
        this.dynamicFieldId = dynamicFieldId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecruitSelectionTypeFieldId) ) return false;
		 RecruitSelectionTypeFieldId castOther = ( RecruitSelectionTypeFieldId ) other; 
         
		 return (this.getSelectionTypeId()==castOther.getSelectionTypeId())
 && (this.getDynamicFieldId()==castOther.getDynamicFieldId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getSelectionTypeId();
         result = 37 * result + (int) this.getDynamicFieldId();
         return result;
   }   


}


