package com.inkubator.hrm.entity;
// Generated Jun 16, 2014 8:44:01 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecruitSelectionApplicantPassedId generated by hbm2java
 */
@Embeddable
public class RecruitSelectionApplicantPassedId implements java.io.Serializable {

	private long applicantId;
	private long hireApplyId;

	public RecruitSelectionApplicantPassedId() {
	}

	public RecruitSelectionApplicantPassedId(long hireApplyId, long applicantId) {
		this.applicantId = applicantId;
		this.hireApplyId = hireApplyId;
	}

	@Column(name = "applicant_id", nullable = false)
	public long getApplicantId() {
		return applicantId;
	}

	public void setApplicantId(long applicantId) {
		this.applicantId = applicantId;
	}

	@Column(name = "hire_apply_id", nullable = false)
	public long getHireApplyId() {
		return hireApplyId;
	}

	public void setHireApplyId(long hireApplyId) {
		this.hireApplyId = hireApplyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecruitSelectionApplicantPassedId))
			return false;
		RecruitSelectionApplicantPassedId castOther = (RecruitSelectionApplicantPassedId) other;

		return (this.getApplicantId() == castOther.getApplicantId())
				&& (this.getHireApplyId() == castOther.getHireApplyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getApplicantId();
		result = 37 * result + (int) this.getHireApplyId();
		return result;
	}

}
