package com.inkubator.hrm.entity;
// Generated Oct 26, 2015 11:22:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * RecruitSelectionApplicantInitial generated by hbm2java
 */
@Entity
@Table(name="recruit_selection_applicant_initial"
    ,catalog="hrm", uniqueConstraints = @UniqueConstraint(columnNames = {"applicant_id", "hire_apply_id"})
)
public class RecruitSelectionApplicantInitial  implements java.io.Serializable {


     private long id;
     private Integer version;
     private RecruitApplicant recruitApplicant;
     private RecruitHireApply recruitHireApply;
     private Date createdOn;
     private String createdBy;

    public RecruitSelectionApplicantInitial() {
    }

	
    public RecruitSelectionApplicantInitial(long id, RecruitApplicant recruitApplicant, RecruitHireApply recruitHireApply) {
        this.id = id;
        this.recruitApplicant = recruitApplicant;
        this.recruitHireApply = recruitHireApply;
    }
    public RecruitSelectionApplicantInitial(long id, RecruitApplicant recruitApplicant, RecruitHireApply recruitHireApply, Date createdOn, String createdBy) {
       this.id = id;
       this.recruitApplicant = recruitApplicant;
       this.recruitHireApply = recruitHireApply;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="applicant_id", nullable=false)
    public RecruitApplicant getRecruitApplicant() {
        return this.recruitApplicant;
    }
    
    public void setRecruitApplicant(RecruitApplicant recruitApplicant) {
        this.recruitApplicant = recruitApplicant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hire_apply_id", nullable=false)
    public RecruitHireApply getRecruitHireApply() {
        return this.recruitHireApply;
    }
    
    public void setRecruitHireApply(RecruitHireApply recruitHireApply) {
        this.recruitHireApply = recruitHireApply;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

}


