package com.inkubator.hrm.entity;
// Generated Apr 15, 2015 4:13:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RecruitmenSelectionSeriesDetail generated by hbm2java
 */
@Entity
@Table(name="recruitmen_selection_series_detail"
    ,catalog="hrm"
)
public class RecruitmenSelectionSeriesDetail  implements java.io.Serializable {


     private long recruitmenSelectionSeriesId;
     private Integer version;
     private RecruitmenSelectionSeries recruitmenSelectionSeries;
     private SystemLetterReference systemLetterReferenceByRejectLetterId;
     private SystemLetterReference systemLetterReferenceByAcceptLetterId;
     private String note;
     private String createdBy;
     private Date createdOn;
     private String updatedOn;
     private Date updatedBy;

    public RecruitmenSelectionSeriesDetail() {
    }

	
    public RecruitmenSelectionSeriesDetail(long recruitmenSelectionSeriesId) {
        this.recruitmenSelectionSeriesId = recruitmenSelectionSeriesId;
    }
    public RecruitmenSelectionSeriesDetail(long recruitmenSelectionSeriesId, RecruitmenSelectionSeries recruitmenSelectionSeries, SystemLetterReference systemLetterReferenceByRejectLetterId, SystemLetterReference systemLetterReferenceByAcceptLetterId, String note, String createdBy, Date createdOn, String updatedOn, Date updatedBy) {
       this.recruitmenSelectionSeriesId = recruitmenSelectionSeriesId;
       this.recruitmenSelectionSeries = recruitmenSelectionSeries;
       this.systemLetterReferenceByRejectLetterId = systemLetterReferenceByRejectLetterId;
       this.systemLetterReferenceByAcceptLetterId = systemLetterReferenceByAcceptLetterId;
       this.note = note;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="recruitmen_selection_series_id", unique=true, nullable=false)
    public long getRecruitmenSelectionSeriesId() {
        return this.recruitmenSelectionSeriesId;
    }
    
    public void setRecruitmenSelectionSeriesId(long recruitmenSelectionSeriesId) {
        this.recruitmenSelectionSeriesId = recruitmenSelectionSeriesId;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="selection_type_id")
    public RecruitmenSelectionSeries getRecruitmenSelectionSeries() {
        return this.recruitmenSelectionSeries;
    }
    
    public void setRecruitmenSelectionSeries(RecruitmenSelectionSeries recruitmenSelectionSeries) {
        this.recruitmenSelectionSeries = recruitmenSelectionSeries;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="reject_letter_id")
    public SystemLetterReference getSystemLetterReferenceByRejectLetterId() {
        return this.systemLetterReferenceByRejectLetterId;
    }
    
    public void setSystemLetterReferenceByRejectLetterId(SystemLetterReference systemLetterReferenceByRejectLetterId) {
        this.systemLetterReferenceByRejectLetterId = systemLetterReferenceByRejectLetterId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accept_letter_id")
    public SystemLetterReference getSystemLetterReferenceByAcceptLetterId() {
        return this.systemLetterReferenceByAcceptLetterId;
    }
    
    public void setSystemLetterReferenceByAcceptLetterId(SystemLetterReference systemLetterReferenceByAcceptLetterId) {
        this.systemLetterReferenceByAcceptLetterId = systemLetterReferenceByAcceptLetterId;
    }

    
    @Column(name="note")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_on", length=45)
    public String getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(String updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_by", length=19)
    public Date getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Date updatedBy) {
        this.updatedBy = updatedBy;
    }




}


