package com.inkubator.hrm.entity;
// Generated Jun 11, 2014 1:55:24 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RiwayatAkses generated by hbm2java
 */
@Entity
@Table(name = "riwayat_akses", catalog="hrm_payroll_backup"
)
public class RiwayatAkses implements java.io.Serializable {

    private long id;
    private String userId;
    private String pathUrl;
    private Date dateAccess;
    private String name;

    public RiwayatAkses() {
    }

    public RiwayatAkses(long id) {
        this.id = id;
    }

    public RiwayatAkses(long id, String userId, String pathUrl, Date dateAccess) {
        this.id = id;
        this.userId = userId;
        this.pathUrl = pathUrl;
        this.dateAccess = dateAccess;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "user_id", length = 45)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "path_url", length = 150)
    public String getPathUrl() {
        return this.pathUrl;
    }

    public void setPathUrl(String pathUrl) {
        this.pathUrl = pathUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_access", length = 19)
    public Date getDateAccess() {
        return this.dateAccess;
    }

    public void setDateAccess(Date dateAccess) {
        this.dateAccess = dateAccess;
    }

    @Column(name = "name_path", length = 45)
    public String getName() {
   
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
