package com.inkubator.hrm.entity;

// Generated Mar 13, 2015 9:01:09 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RmbsSchema generated by hbm2java
 */
@Entity
@Table(name = "rmbs_schema", catalog = "hrm")
public class RmbsSchema implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String code;
	private String name;
	private String description;
	private String nomorSk;
	private Double maxTotalReimburst;
	private Double maxWithReceiptPerType;
	private Double maxWithoutReceiptPerType;
	private Integer noticeForLimit;
	private Integer submissionDeadline;
	private Boolean isActive;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private Set<RmbsSchemaListOfEmp> rmbsSchemaListOfEmps = new HashSet<RmbsSchemaListOfEmp>(0);
	private Set<RmbsSchemaListOfType> rmbsSchemaListOfTypes = new HashSet<RmbsSchemaListOfType>(0);
	private Set<ApprovalDefinitionRmbsSchema> approvalDefinitionRmbsSchemas = new HashSet<ApprovalDefinitionRmbsSchema>(0);

	public RmbsSchema() {
	}

	public RmbsSchema(long id) {
		this.id = id;
	}

	@Id
    @Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
    @Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "code", unique = true, nullable = false, length = 12)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", unique = true, nullable = false, length = 60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535, columnDefinition = "Text")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "nomor_sk", unique = true, nullable = false, length = 60)
	public String getNomorSk() {
		return this.nomorSk;
	}

	public void setNomorSk(String nomorSk) {
		this.nomorSk = nomorSk;
	}

	@Column(name = "max_total_reimburst", nullable = false)
	public Double getMaxTotalReimburst() {
		return this.maxTotalReimburst;
	}

	public void setMaxTotalReimburst(Double maxTotalReimburst) {
		this.maxTotalReimburst = maxTotalReimburst;
	}

	@Column(name = "max_with_receipt_per_type", nullable = false)
	public Double getMaxWithReceiptPerType() {
		return this.maxWithReceiptPerType;
	}
	
	public void setMaxWithReceiptPerType(Double maxWithReceiptPerType) {
		this.maxWithReceiptPerType = maxWithReceiptPerType;
	}

	@Column(name = "max_without_receipt_per_type", nullable = false)
	public Double getMaxWithoutReceiptPerType() {
		return this.maxWithoutReceiptPerType;
	}

	public void setMaxWithoutReceiptPerType(Double maxWithoutReceiptPerType) {
		this.maxWithoutReceiptPerType = maxWithoutReceiptPerType;
	}

	@Column(name = "notice_for_limit", nullable = false, length = 3)
	public Integer getNoticeForLimit() {
		return this.noticeForLimit;
	}

	public void setNoticeForLimit(Integer noticeForLimit) {
		this.noticeForLimit = noticeForLimit;
	}		
	
	@Column(name = "submission_deadline", nullable = false, length = 3)
	public Integer getSubmissionDeadline() {
		return submissionDeadline;
	}

	public void setSubmissionDeadline(Integer submissionDeadline) {
		this.submissionDeadline = submissionDeadline;
	}

	@Column(name = "is_active", nullable = false)
	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rmbsSchema")
	public Set<RmbsSchemaListOfEmp> getRmbsSchemaListOfEmps() {
		return this.rmbsSchemaListOfEmps;
	}

	public void setRmbsSchemaListOfEmps(Set<RmbsSchemaListOfEmp> rmbsSchemaListOfEmps) {
		this.rmbsSchemaListOfEmps = rmbsSchemaListOfEmps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rmbsSchema", cascade=CascadeType.REMOVE)
	public Set<RmbsSchemaListOfType> getRmbsSchemaListOfTypes() {
		return this.rmbsSchemaListOfTypes;
	}

	public void setRmbsSchemaListOfTypes(Set<RmbsSchemaListOfType> rmbsSchemaListOfTypes) {
		this.rmbsSchemaListOfTypes = rmbsSchemaListOfTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rmbsSchema", cascade=CascadeType.REMOVE)
	public Set<ApprovalDefinitionRmbsSchema> getApprovalDefinitionRmbsSchemas() {
		return approvalDefinitionRmbsSchemas;
	}

	public void setApprovalDefinitionRmbsSchemas(Set<ApprovalDefinitionRmbsSchema> approvalDefinitionRmbsSchemas) {
		this.approvalDefinitionRmbsSchemas = approvalDefinitionRmbsSchemas;
	}
	
	

}
