package com.inkubator.hrm.entity;

// Generated Mar 13, 2015 9:01:09 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RmbsType generated by hbm2java
 */
@Entity
@Table(name = "rmbs_type", catalog = "hrm")
public class RmbsType implements java.io.Serializable {

	private Long id;
	private Integer version;
	private CostCenter costCenter;
	private String code;
	private String name;
	private String description;
	private Integer roundDigit;
	private Boolean isActive;
	private Integer daysOfAvailable;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private Set<RmbsSchemaListOfType> rmbsSchemaListOfTypes = new HashSet<RmbsSchemaListOfType>(0);

	public RmbsType() {
	}

	public RmbsType(Long id) {
		this.id = id;
	}

	@Id
    @Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
    @Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "coa_id", nullable = false)
	public CostCenter getCostCenter() {
		return costCenter;
	}

	public void setCostCenter(CostCenter costCenter) {
		this.costCenter = costCenter;
	}

	@Column(name = "code", unique = true, nullable = false, length = 12)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", unique = true, nullable = false, length = 60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535, columnDefinition = "Text")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "round_digit", nullable = false)
	public Integer getRoundDigit() {
		return this.roundDigit;
	}

	public void setRoundDigit(Integer roundDigit) {
		this.roundDigit = roundDigit;
	}

	@Column(name = "is_active", nullable = false)
	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "days_of_available", length = 3)
	public Integer getDaysOfAvailable() {
		return daysOfAvailable;
	}

	public void setDaysOfAvailable(Integer daysOfAvailable) {
		this.daysOfAvailable = daysOfAvailable;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rmbsType")
	public Set<RmbsSchemaListOfType> getRmbsSchemaListOfTypes() {
		return this.rmbsSchemaListOfTypes;
	}

	public void setRmbsSchemaListOfTypes(Set<RmbsSchemaListOfType> rmbsSchemaListOfTypes) {
		this.rmbsSchemaListOfTypes = rmbsSchemaListOfTypes;
	}

}
