package com.inkubator.hrm.entity;
// Generated Oct 1, 2015 11:21:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchedulerLog generated by hbm2java
 */
@Entity
@Table(name="scheduler_log"
    ,catalog="hrm"
)
public class SchedulerLog  implements java.io.Serializable {


     private long id;
     private SchedulerConfig schedulerConfig;
     private Date executionDate;
     private String statusMessages;

    public SchedulerLog() {
    }

	
    public SchedulerLog(long id) {
        this.id = id;
    }
    public SchedulerLog(long id, SchedulerConfig schedulerConfig, Date executionDate, String statusMessages) {
       this.id = id;
       this.schedulerConfig = schedulerConfig;
       this.executionDate = executionDate;
       this.statusMessages = statusMessages;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="scheduler_config_id")
    public SchedulerConfig getSchedulerConfig() {
        return this.schedulerConfig;
    }
    
    public void setSchedulerConfig(SchedulerConfig schedulerConfig) {
        this.schedulerConfig = schedulerConfig;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="execution_date", length=19)
    public Date getExecutionDate() {
        return this.executionDate;
    }
    
    public void setExecutionDate(Date executionDate) {
        this.executionDate = executionDate;
    }

    
    @Column(name="status_messages", length=100)
    public String getStatusMessages() {
        return this.statusMessages;
    }
    
    public void setStatusMessages(String statusMessages) {
        this.statusMessages = statusMessages;
    }




}


