package com.inkubator.hrm.entity;
// Generated Apr 15, 2015 4:13:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * SystemLetterReference generated by hbm2java
 */
@Entity
@Table(name="system_letter_reference"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class SystemLetterReference  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String code;
     private String name;
     private byte[] uploadData;
     private String letterSumary;
     private String description;
     private Date effectiveDate;
     private String fileUploadName;
     private boolean isActive;
     private String content;
     private Date createdOn;
     private String createdBy;
     private Date updatedOn;
     private String updatedBy;
     private Integer groupReference;

    public SystemLetterReference() {
    }

    
	
    public SystemLetterReference(long id) {
		this.id = id;
	}



	public SystemLetterReference(long id, String code, String name, boolean isActive) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.isActive = isActive;
    }
    public SystemLetterReference(long id, String code, String name, byte[] uploadData, String letterSumary, String description, Date effectiveDate, String fileUploadName, boolean isActive, String content, Date createdOn, String createdBy, Date updatedOn, String updatedBy, Integer groupReference) {
       this.id = id;
       this.code = code;
       this.name = name;
       this.uploadData = uploadData;
       this.letterSumary = letterSumary;
       this.description = description;
       this.effectiveDate = effectiveDate;
       this.fileUploadName = fileUploadName;
       this.isActive = isActive;
       this.content = content;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedOn = updatedOn;
       this.updatedBy = updatedBy;
       this.groupReference = groupReference;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="code", unique=true, nullable=false, length=18)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=125)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="upload_data")
    public byte[] getUploadData() {
        return this.uploadData;
    }
    
    public void setUploadData(byte[] uploadData) {
        this.uploadData = uploadData;
    }

    
    @Column(name="letter_sumary")
    public String getLetterSumary() {
        return this.letterSumary;
    }
    
    public void setLetterSumary(String letterSumary) {
        this.letterSumary = letterSumary;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="effective_date", length=10)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    
    @Column(name="file_upload_name")
    public String getFileUploadName() {
        return this.fileUploadName;
    }
    
    public void setFileUploadName(String fileUploadName) {
        this.fileUploadName = fileUploadName;
    }

    
    @Column(name="is_active", nullable=false)
    public boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="content", length=65535, columnDefinition="Text")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    
    @Column(name="group_reference")
    public Integer getGroupReference() {
        return this.groupReference;
    }
    
    public void setGroupReference(Integer groupReference) {
        this.groupReference = groupReference;
    }

}


