package com.inkubator.hrm.entity;
// Generated Dec 5, 2014 9:54:53 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TempUnregPayroll generated by hbm2java
 */
@Entity
@Table(name = "temp_unreg_payroll", catalog="hrm_payroll_backup"
)
public class TempUnregPayroll implements java.io.Serializable {

    private long id;
    private Integer version;
    private UnregSalary unregSalary;
    private EmpData empData;
    private PaySalaryComponent paySalaryComponent;
    private Integer factor;
    private BigDecimal nominal;
    private Date createdOn;
    private String createdBy;
    private String updatedBy;
    private Date updatedOn;

    public TempUnregPayroll() {
    }

    public TempUnregPayroll(long id) {
        this.id = id;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
        
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unreg_salary_id", nullable = false)
    public UnregSalary getUnregSalary() {
		return unregSalary;
	}

	public void setUnregSalary(UnregSalary unregSalary) {
		this.unregSalary = unregSalary;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_data_id", nullable = false)
    public EmpData getEmpData() {
        return this.empData;
    }

    public void setEmpData(EmpData empData) {
        this.empData = empData;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pay_salary_component_id", nullable = false)
    public PaySalaryComponent getPaySalaryComponent() {
		return paySalaryComponent;
	}

	public void setPaySalaryComponent(PaySalaryComponent paySalaryComponent) {
		this.paySalaryComponent = paySalaryComponent;
	}

    @Column(name = "nominal", precision = 10, scale = 0, nullable = false)
    public BigDecimal getNominal() {
        return this.nominal;
    }

    public void setNominal(BigDecimal nominal) {
        this.nominal = nominal;
    }     
        
    @Column(name = "factor")
	public Integer getFactor() {
		return factor;
	}

	public void setFactor(Integer factor) {
		this.factor = factor;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

}
