package com.inkubator.hrm.entity;
// Generated Dec 30, 2014 11:22:24 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UnregPayComponentsExceptionId generated by hbm2java
 */
@Embeddable
public class UnregPayComponentsExceptionId  implements java.io.Serializable {


     private long unregId;
     private long paySalaryCompId;
     private long empDataId;

    public UnregPayComponentsExceptionId() {
    }

    public UnregPayComponentsExceptionId(long unregId, long paySalaryCompId, long empDataId) {
       this.unregId = unregId;
       this.paySalaryCompId = paySalaryCompId;
       this.empDataId = empDataId;
    }
   


    @Column(name="unreg_id", nullable=false)
    public long getUnregId() {
        return this.unregId;
    }
    
    public void setUnregId(long unregId) {
        this.unregId = unregId;
    }


    @Column(name="pay_salary_comp_id", nullable=false)
    public long getPaySalaryCompId() {
        return this.paySalaryCompId;
    }
    
    public void setPaySalaryCompId(long paySalaryCompId) {
        this.paySalaryCompId = paySalaryCompId;
    }


    @Column(name="emp_data_id", nullable=false)
    public long getEmpDataId() {
        return this.empDataId;
    }
    
    public void setEmpDataId(long empDataId) {
        this.empDataId = empDataId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UnregPayComponentsExceptionId) ) return false;
		 UnregPayComponentsExceptionId castOther = ( UnregPayComponentsExceptionId ) other; 
         
		 return (this.getUnregId()==castOther.getUnregId())
 && (this.getPaySalaryCompId()==castOther.getPaySalaryCompId())
 && (this.getEmpDataId()==castOther.getEmpDataId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUnregId();
         result = 37 * result + (int) this.getPaySalaryCompId();
         result = 37 * result + (int) this.getEmpDataId();
         return result;
   }   


}


