package com.inkubator.hrm.entity;
// Generated Dec 24, 2014 8:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UnregEmpTypeId generated by hbm2java
 */
@Embeddable
public class UnregEmpTypeId  implements java.io.Serializable {


     private long unregId;
     private long unregEmpTypeId;

    public UnregEmpTypeId() {
    }

    public UnregEmpTypeId(long unregId, long unregEmpTypeId) {
       this.unregId = unregId;
       this.unregEmpTypeId = unregEmpTypeId;
    }
   


    @Column(name="unreg_id", nullable=false)
    public long getUnregId() {
        return this.unregId;
    }
    
    public void setUnregId(long unregId) {
        this.unregId = unregId;
    }


    @Column(name="unreg_emp_type_id", nullable=false)
    public long getUnregEmpTypeId() {
        return this.unregEmpTypeId;
    }
    
    public void setUnregEmpTypeId(long unregEmpTypeId) {
        this.unregEmpTypeId = unregEmpTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UnregEmpTypeId) ) return false;
		 UnregEmpTypeId castOther = ( UnregEmpTypeId ) other; 
         
		 return (this.getUnregId()==castOther.getUnregId())
 && (this.getUnregEmpTypeId()==castOther.getUnregEmpTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUnregId();
         result = 37 * result + (int) this.getUnregEmpTypeId();
         return result;
   }   


}


