package com.inkubator.hrm.entity;
// Generated Dec 24, 2014 8:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UnregDepartementId generated by hbm2java
 */
@Embeddable
public class UnregDepartementId  implements java.io.Serializable {


     private long unregPayId;
     private long unregDepartementId;

    public UnregDepartementId() {
    }

    public UnregDepartementId(long unregPayId, long unregDepartementId) {
       this.unregPayId = unregPayId;
       this.unregDepartementId = unregDepartementId;
    }
   


    @Column(name="unreg_pay_id", nullable=false)
    public long getUnregPayId() {
        return this.unregPayId;
    }
    
    public void setUnregPayId(long unregPayId) {
        this.unregPayId = unregPayId;
    }


    @Column(name="unreg_departement_id", nullable=false)
    public long getUnregDepartementId() {
        return this.unregDepartementId;
    }
    
    public void setUnregDepartementId(long unregDepartementId) {
        this.unregDepartementId = unregDepartementId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UnregDepartementId) ) return false;
		 UnregDepartementId castOther = ( UnregDepartementId ) other; 
         
		 return (this.getUnregPayId()==castOther.getUnregPayId())
 && (this.getUnregDepartementId()==castOther.getUnregDepartementId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUnregPayId();
         result = 37 * result + (int) this.getUnregDepartementId();
         return result;
   }   


}


