package com.inkubator.hrm.entity;
// Generated Dec 24, 2014 8:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * UnregEmpReligion generated by hbm2java
 */
@Entity
@Table(name="unreg_emp_religion"
    ,catalog="hrm"
)
public class UnregEmpReligion  implements java.io.Serializable {


     private UnregEmpReligionId id;
     private Integer version;
     private Religion religion;
     private UnregSalary unregSalary;
     private String descriptions;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updateedOn;

    public UnregEmpReligion() {
    }

	
    public UnregEmpReligion(UnregEmpReligionId id, Religion religion, UnregSalary unregSalary) {
        this.id = id;
        this.religion = religion;
        this.unregSalary = unregSalary;
    }
    public UnregEmpReligion(UnregEmpReligionId id, Religion religion, UnregSalary unregSalary, String descriptions, String createdBy, Date createdOn, String updatedBy, Date updateedOn) {
       this.id = id;
       this.religion = religion;
       this.unregSalary = unregSalary;
       this.descriptions = descriptions;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updateedOn = updateedOn;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="unregId", column=@Column(name="unreg_id", nullable=false) ), 
        @AttributeOverride(name="religionId", column=@Column(name="religion_id", nullable=false) ) } )
    public UnregEmpReligionId getId() {
        return this.id;
    }
    
    public void setId(UnregEmpReligionId id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="religion_id", nullable=false, insertable=false, updatable=false)
    public Religion getReligion() {
        return this.religion;
    }
    
    public void setReligion(Religion religion) {
        this.religion = religion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unreg_id", nullable=false, insertable=false, updatable=false)
    public UnregSalary getUnregSalary() {
        return this.unregSalary;
    }
    
    public void setUnregSalary(UnregSalary unregSalary) {
        this.unregSalary = unregSalary;
    }

    
    @Column(name="descriptions", length=65535)
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updateed_on", length=19)
    public Date getUpdateedOn() {
        return this.updateedOn;
    }
    
    public void setUpdateedOn(Date updateedOn) {
        this.updateedOn = updateedOn;
    }




}


