package com.inkubator.hrm.entity;
// Generated Jun 10, 2015 1:00:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * WtHitungLemburJam generated by hbm2java
 */
@Entity
@Table(name="wt_hitung_lembur_jam"
    ,catalog="hrm_payroll"
)
public class WtHitungLemburJam  implements java.io.Serializable {


     private int id;
     private Integer version;
     private WtHitungLembur wtHitungLembur;
     private Integer jamKe;
     private BigDecimal hariKerja;
     private BigDecimal hariLibur;
     private BigDecimal hariRaya;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public WtHitungLemburJam() {
    }

	
    public WtHitungLemburJam(int id) {
        this.id = id;
    }
    public WtHitungLemburJam(int id, WtHitungLembur wtHitungLembur, Integer jamKe, BigDecimal hariKerja, BigDecimal hariLibur, BigDecimal hariRaya, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.id = id;
       this.wtHitungLembur = wtHitungLembur;
       this.jamKe = jamKe;
       this.hariKerja = hariKerja;
       this.hariLibur = hariLibur;
       this.hariRaya = hariRaya;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hitung_lembur_id")
    public WtHitungLembur getWtHitungLembur() {
        return this.wtHitungLembur;
    }
    
    public void setWtHitungLembur(WtHitungLembur wtHitungLembur) {
        this.wtHitungLembur = wtHitungLembur;
    }

    
    @Column(name="jam_ke")
    public Integer getJamKe() {
        return this.jamKe;
    }
    
    public void setJamKe(Integer jamKe) {
        this.jamKe = jamKe;
    }

    
    @Column(name="hari_kerja", precision=2, scale=1)
    public BigDecimal getHariKerja() {
        return this.hariKerja;
    }
    
    public void setHariKerja(BigDecimal hariKerja) {
        this.hariKerja = hariKerja;
    }

    
    @Column(name="hari_libur", precision=2, scale=1)
    public BigDecimal getHariLibur() {
        return this.hariLibur;
    }
    
    public void setHariLibur(BigDecimal hariLibur) {
        this.hariLibur = hariLibur;
    }

    
    @Column(name="hari_raya", precision=2, scale=1)
    public BigDecimal getHariRaya() {
        return this.hariRaya;
    }
    
    public void setHariRaya(BigDecimal hariRaya) {
        this.hariRaya = hariRaya;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


