package com.inkubator.hrm.entity;
// Generated May 21, 2014 4:59:40 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * WtHoliday generated by hbm2java
 */
@Entity
@Table(name = "wt_holiday", catalog = "hrm_personalia", uniqueConstraints = @UniqueConstraint(columnNames = "holiday_name")
)
public class WtHoliday implements java.io.Serializable {

    private long id;
    private Integer version;
    private Religion religion;
    private String holidayName;
    private Date holidayDate;
    private Integer isEveryYear;
    private Integer isColectiveLeave;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;

    public WtHoliday() {
    }

    public WtHoliday(long id) {
        this.id = id;
    }

    public WtHoliday(long id, Religion religion, String holidayName, Date holidayDate, Integer isEveryYear, Integer isColectiveLeave, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
        this.id = id;
        this.religion = religion;
        this.holidayName = holidayName;
        this.holidayDate = holidayDate;
        this.isEveryYear = isEveryYear;
        this.isColectiveLeave = isColectiveLeave;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "religion_id")
    public Religion getReligion() {
        return this.religion;
    }

    public void setReligion(Religion religion) {
        this.religion = religion;
    }

    @Column(name = "holiday_name", unique = true, length = 45)
    public String getHolidayName() {
        return this.holidayName;
    }

    public void setHolidayName(String holidayName) {
        this.holidayName = holidayName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "holiday_date", length = 10)
    public Date getHolidayDate() {
        return this.holidayDate;
    }

    public void setHolidayDate(Date holidayDate) {
        this.holidayDate = holidayDate;
    }

    @Column(name = "is_every_year")
    public Integer getIsEveryYear() {
        return this.isEveryYear;
    }

    public void setIsEveryYear(Integer isEveryYear) {
        this.isEveryYear = isEveryYear;
    }

    @Column(name = "is_colective_leave")
    public Integer getIsColectiveLeave() {
        return this.isColectiveLeave;
    }

    public void setIsColectiveLeave(Integer isColectiveLeave) {
        this.isColectiveLeave = isColectiveLeave;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Transient
    public String getIsEveryYearAsLabel() {
        if (isEveryYear == 1) {
            return "Y";
        }

        if (isEveryYear == 0) {
            return "N";
        }
        return null;
    }

    @Transient
    public String getIsCollectiveAsLabel() {
        if (isColectiveLeave == 1) {
            return "Y";
        }

        if (isColectiveLeave == 0) {
            return "N";
        }
        return null;
    }

}
