package com.inkubator.hrm.entity;
// Generated Jun 4, 2014 10:50:27 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * WtScheduleShift generated by hbm2java
 */
@Entity
@Table(name="wt_schedule_shift"
    ,catalog="hrm_personalia"
)
public class WtScheduleShift  implements java.io.Serializable {


     private long id;
     private Integer version;
     private WtGroupWorking wtGroupWorking;
     private WtWorkingHour wtWorkingHour;
     private Date scheduleDate;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public WtScheduleShift() {
    }

	
    public WtScheduleShift(long id) {
        this.id = id;
    }
    public WtScheduleShift(long id, WtGroupWorking wtGroupWorking, WtWorkingHour wtWorkingHour, Date scheduleDate, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.id = id;
       this.wtGroupWorking = wtGroupWorking;
       this.wtWorkingHour = wtWorkingHour;
       this.scheduleDate = scheduleDate;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_working_id")
    public WtGroupWorking getWtGroupWorking() {
        return this.wtGroupWorking;
    }
    
    public void setWtGroupWorking(WtGroupWorking wtGroupWorking) {
        this.wtGroupWorking = wtGroupWorking;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="working_hour_id")
    public WtWorkingHour getWtWorkingHour() {
        return this.wtWorkingHour;
    }
    
    public void setWtWorkingHour(WtWorkingHour wtWorkingHour) {
        this.wtWorkingHour = wtWorkingHour;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="schedule_date", length=19)
    public Date getScheduleDate() {
        return this.scheduleDate;
    }
    
    public void setScheduleDate(Date scheduleDate) {
        this.scheduleDate = scheduleDate;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


